# データ読込

In [1]:
# ローカルユーティリティ: 外部ディレクトリ(utils, logic)への依存を排除
import pandas as pd
import sqlite3
from datetime import datetime, date, timedelta
from typing import Union, List
import jpholiday

# 日本の祝日取得（jpholiday が無ければ空集合）
def get_japanese_holidays(
    start: Union[str, date], end: Union[str, date], as_str: bool = True
) -> Union[List[str], List[date]]:
    """
    指定した期間の日本の祝日を取得する関数。

    Args:
        start (str or date): 開始日（"YYYY-MM-DD" または date型）
        end (str or date): 終了日（"YYYY-MM-DD" または date型）
        as_str (bool): Trueなら"YYYY-MM-DD"形式、Falseならdate型

    Returns:
        Union[List[str], List[date]]: 祝日のリスト（文字列またはdate型）
    """
    # --- 日付型でなければ変換 ---
    if isinstance(start, str):
        start = datetime.strptime(start, "%Y-%m-%d").date()
    if isinstance(end, str):
        end = datetime.strptime(end, "%Y-%m-%d").date()

    # --- 日付範囲の祝日抽出 ---
    holidays = [
        d
        for d in (start + timedelta(days=i) for i in range((end - start).days + 1))
        if jpholiday.is_holiday(d)
    ]

    return [d.strftime("%Y-%m-%d") for d in holidays] if as_str else holidays

# 日本語フォント設定（存在する最初の候補を適用）
def set_jp_font():
    try:
        import matplotlib.pyplot as plt
        from matplotlib import font_manager
        candidates = ["IPAexGothic", "IPAGothic", "Noto Sans CJK JP", "TakaoGothic"]
        system_fonts = font_manager.findSystemFonts()
        for cand in candidates:
            for f in system_fonts:
                if cand in f:
                    plt.rcParams["font.family"] = cand
                    return
    except Exception:
        pass  # フォント設定失敗は無視

# SQLite から重量データを読む（テーブル名は推測。存在するテーブルに合わせて変更可）
def load_data_from_sqlite(db_path="/work/app/data/factory_manage/weight_data.db", table_name="weight_data"):
    with sqlite3.connect(db_path) as conn:
        # テーブル存在チェック & 自動選択
        try:
            df_tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", conn)
            if table_name not in df_tables['name'].tolist() and len(df_tables):
                # 最初のテーブルを利用
                table_name_local = df_tables['name'].iloc[0]
            else:
                table_name_local = table_name
        except Exception:
            table_name_local = table_name
        df_local = pd.read_sql(f"SELECT * FROM {table_name_local}", conn)
    # 日付カラム推測
    for col in ["伝票日付", "date", "dt"]:
        if col in df_local.columns:
            try:
                df_local[col] = pd.to_datetime(df_local[col])
            except Exception:
                pass
    return df_local

set_jp_font()
print("[INFO] ローカルユーティリティを読み込みました。")

# モジュールキャッシュのクリア（new_model1/new_model2 が部分的に読み込まれている場合に対応）
import sys, importlib
for name in list(sys.modules.keys()):
    if name.startswith('new_model1') or name.startswith('new_model2'):
        del sys.modules[name]
# 足りなければ /works/scripts を先頭に追加してからロード
sys.path.insert(0, '/works/scripts')
try:
    import new_model1
    importlib.reload(new_model1)
    print('reloaded new_model1 from', getattr(new_model1, '__file__', None))
except Exception as e:
    print('reload new_model1 failed:', e)
try:
    import new_model2
    importlib.reload(new_model2)
    print('reloaded new_model2 from', getattr(new_model2, '__file__', None))
except Exception as e:
    print('reload new_model2 failed:', e)

[INFO] ローカルユーティリティを読み込みました。
reloaded new_model1 from /works/scripts/new_model1/__init__.py
reloaded new_model2 from /works/scripts/new_model2/__init__.py
reloaded new_model1 from /works/scripts/new_model1/__init__.py
reloaded new_model2 from /works/scripts/new_model2/__init__.py

In [2]:
import pandas as pd
# from logic.factory_manage.utils.sql import load_data_from_sqlite  # 外部依存 -> ローカル版へ
# from utils.get_holydays import get_japanese_holidays             # 外部依存 -> ローカル版へ

# from utils.font import set_jp_font  # 外部フォント設定 -> ローカル版
# set_jp_font()  # 既に前セルで実行済み

# CSV / DB 読み込み（パスはPRE_HANNNYU配下に限定）
# path = "/works/data/factory_manage/weight_data.db"  # そのまま利用

# df = load_data_from_sqlite(path)
# df["伝票日付"].max()
# df.head()

### 2021年～

In [3]:
# pdは既にCELL INDEX:1でimportされているので、そのまま使えます
df_2021 = pd.read_csv("/works/data/input/2020顧客.csv", encoding="utf-8")
df_2022 = pd.read_csv("/works/data/input/2022顧客.csv", encoding="utf-8")
df_2023 = pd.read_csv("/works/data/input/2023_all.csv", encoding="utf-8")
df_2024 = pd.read_csv("/works/data/input/20240501-20250422.csv", encoding="utf-8")

df_2021 = df_2021[['伝票日付', '商品', '正味重量']]
df_2022 = df_2022[['伝票日付', '商品', '正味重量']]
df_2023 = df_2023[['伝票日付', '商品', '正味重量']]
df_2021.rename(columns={'商品': '品名'}, inplace=True)
df_2022.rename(columns={'商品': '品名'}, inplace=True)
df_2023.rename(columns={'商品': '品名'}, inplace=True)
df_2024 = df_2024[['伝票日付', '品名', '正味重量']]

df_all = pd.concat([df_2021, df_2022, df_2023, df_2024], ignore_index=True)
# 曜日など () を削除
df_all["伝票日付"] = df_all["伝票日付"].str.replace(r"\(.*\)", "", regex=True)
df_all["伝票日付"] = pd.to_datetime(df_all["伝票日付"], format="%Y/%m/%d")
df_all

/tmp/ipykernel_69458/1970061802.py:4: DtypeWarning: Columns (68) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv("/works/data/input/2023_all.csv", encoding="utf-8")

             伝票日付               品名    正味重量
0      2020-01-04           混合廃棄物A   870.0
1      2020-01-04           混合廃棄物A   450.0
2      2020-01-04       混合廃棄物（焼却物）  2400.0
3      2020-01-04           混合廃棄物A   250.0
4      2020-01-04           混合廃棄物A   800.0
...           ...              ...     ...
184245 2025-05-26  軽量物系A(ｽﾀｲﾛﾌｫｰﾑ)    10.0
184246 2025-05-26        廃ﾌﾟﾗｽﾁｯｸ類    30.0
184247 2025-05-26        廃ﾌﾟﾗｽﾁｯｸ類   160.0
184248 2025-05-26           混合廃棄物A  2530.0
184249 2025-05-26   軽量物系B(ｸﾞﾗｽｳｰﾙ)   250.0

[184250 rows x 3 columns]

### 予約情報

In [4]:
df_reserve = pd.read_csv(
    "/works/data/input/yoyaku_data.csv")
df_reserve["予約日"] = pd.to_datetime(df_reserve["予約日"])
df_reserve.rename(columns={"台数": "予約台数"}, inplace=True)
print(df_reserve["予約日"].min(), df_reserve["予約日"].max())
print(df_reserve.columns)
df_reserve

2023-01-04 00:00:00 2025-05-31 00:00:00
Index(['予約日', '予約得意先名', '固定客', '予約台数'], dtype='object')

             予約日      予約得意先名    固定客  予約台数
0     2023-01-04        アンデス  False   1.0
1     2023-01-04  リサイクルレスキュー  False   1.0
2     2023-01-04        山口興業  False   2.0
3     2023-01-04        明和建装  False   1.0
4     2023-01-04     まごころ清掃社  False   1.0
...          ...         ...    ...   ...
45726 2025-05-31   首都高メンテナンス  False   1.0
45727 2025-05-31      シミズオクト  False   1.0
45728 2025-05-31          鈴亀  False   1.0
45729 2025-05-31        鈴木運輸   True   1.0
45730 2025-05-31         ナコジ   True   1.0

[45731 rows x 4 columns]

### 受入番号用

In [5]:
import os
import glob
import pandas as pd

# ディレクトリ内の全CSVファイルパスを取得
csv_dir = "/works/data/input/受入_時刻"
csv_files = glob.glob(os.path.join(csv_dir, "*.csv"))

# 全CSVを読み込んで結合
dfs = []
for f in csv_files:
    df_tmp = pd.read_csv(f)

    # 伝票日付を整形 → 日付型へ変換
    df_tmp["伝票日付"] = df_tmp["伝票日付"].str.replace(r"\(.*?\)", "", regex=True).str.strip()
    df_tmp["伝票日付"] = pd.to_datetime(df_tmp["伝票日付"], format="%Y/%m/%d")

    # 正味重量をカンマ除去して数値化
    df_tmp["正味重量"] = df_tmp["正味重量"].replace({',': ''}, regex=True).astype(float)

    # 受入番号の欠損を埋めて型変換（念のため）
    df_tmp["受入番号"] = df_tmp["受入番号"].fillna(-1).astype(int)

    dfs.append(df_tmp)

df_Ukeire = pd.concat(dfs, ignore_index=True)

# 必要カラムだけ抽出（品名・重量・受入番号）
df_Ukeire = df_Ukeire[["伝票日付", "品名", "正味重量", "受入番号"]].copy()

# 台数カウント準備（日付・品名ごとの受入番号ユニーク数）
df_count = (
    df_Ukeire.groupby(["伝票日付", "品名"])["受入番号"]
    .nunique()
    .reset_index()
    .rename(columns={"受入番号": "台数"})
)

# （参考）結合しておく場合
df_merged = pd.merge(df_Ukeire, df_count, on=["伝票日付", "品名"], how="left")

# リネーム
df_merged.rename(columns={"台数": "搬入済台数"}, inplace=True)

# 結果確認
df_merged

            伝票日付           品名    正味重量   受入番号  搬入済台数
0     2024-12-01       混合廃棄物A  1100.0  31839     25
1     2024-12-01          運搬費     NaN  31839      1
2     2024-12-01       混合廃棄物A   720.0  31851     25
3     2024-12-01       混合廃棄物A  1860.0  31834     25
4     2024-12-01       混合廃棄物A  1060.0  31874     25
...          ...          ...     ...    ...    ...
64680 2025-03-31       混合廃棄物A   170.0  46735     68
64681 2025-03-31           選別    80.0  46735     13
64682 2025-03-31  GC 軽鉄･ｽﾁｰﾙ類   160.0  46735      9
64683 2025-03-31         金属くず   400.0  46656      1
64684 2025-03-31  選別(ｷｬﾋﾞﾈｯﾄ)   650.0  46656      1

[64685 rows x 5 columns]

In [6]:
target_items = ["混合廃棄物A", "混合廃棄物B", "GC 軽鉄･ｽﾁｰﾙ類", "選別", "木くず"]

# 成功・モデル

## 予約数の追加モデル

In [7]:
# new_model1: PRE_HANNNYU/scripts/new_model1 内のローカルモジュールを動的パス追加で利用

import sys, os
SCRIPT_ROOT = "/works/scripts"
if SCRIPT_ROOT not in sys.path:
    sys.path.append(SCRIPT_ROOT)

# robust import

from new_model1 import full_walkforward, ReserveFeatureBuilder


import pandas as pd
from sklearn.metrics import r2_score, mean_absolute_error
import matplotlib.pyplot as plt

In [8]:

# default: do not run full heavy pipeline unless explicitly enabled
RUN_PIPELINE = True

# 閾値（暫定的に緩和して予測生成が行われるか確認）
MIN_STAGE1_DAYS = 20  # 元:30
MIN_STAGE2_DAYS = 10  # 元:15

if RUN_PIPELINE:
    # 予約特徴量生成
    df_reserve_feat = ReserveFeatureBuilder(df_reserve).build()

    # 対象日を予約日に限定 (学習データが足りない場合はこのフィルタを緩めることを検討)
    reserve_dates = df_reserve_feat.index
    df_all["伝票日付"] = pd.to_datetime(df_all["伝票日付"])
    df_all = df_all[df_all["伝票日付"].isin(reserve_dates)].copy()

    print("[DEBUG] reservation_filtered_days=", df_all["伝票日付"].nunique())
    print("[DEBUG] reservation_span=", df_all["伝票日付"].min(), "->", df_all["伝票日付"].max())

    # 評価日数
    days_list = [300]
    results = []
    for days in days_list:
        print(f"\n=== {days}日分のデータで評価中 ===")
        latest_date = df_all["伝票日付"].max()
        cutoff_date = latest_date - pd.Timedelta(days=days)
        df_subset = df_all[df_all["伝票日付"] >= cutoff_date].copy()
        hol_max = df_subset["伝票日付"].max()
        hol_min = df_subset["伝票日付"].min()
        holidays = get_japanese_holidays(hol_min, hol_max)
        print("[DEBUG] df_subset_days=", df_subset["伝票日付"].nunique(), "range=", hol_min, "->", hol_max)
        try:
            actual, pred = full_walkforward(
                df_subset,
                holidays=holidays,
                df_reserve=df_reserve,
                min_stage1_days=MIN_STAGE1_DAYS,
                min_stage2_days=MIN_STAGE2_DAYS,
                top_n=2,
            )
            print(f"[DEBUG] returned_lengths actual={len(actual) if isinstance(actual, list) else 'NA'} pred={len(pred) if isinstance(pred, list) else 'NA'}")
            if isinstance(actual, list) and isinstance(pred, list) and len(actual) > 0 and len(pred) > 0:
                r2 = r2_score(actual, pred)
                mae = mean_absolute_error(actual, pred)
                results.append((days, r2, mae))
                print(f"✅ R² = {r2:.3f}, MAE = {mae:,.0f}kg")
            else:
                print("⚠ 評価に十分なデータがありません (予測件数0)")
                results.append((days, None, None))
        except Exception as e:
            print(f"❌ エラー: {e}")
            results.append((days, None, None))

    # 結果表示
    import pandas as pd

    df_result = pd.DataFrame(results, columns=["days", "R2", "MAE"])
    print("\n=== 評価結果 ===")
    print(df_result)
    if df_result["R2"].notna().any():
        plt.plot(df_result["days"], df_result["R2"], marker="o")
        plt.xlabel("Days")
        plt.ylabel("R² Score")
        plt.title("日数別 R² 評価 (new_model1)")
        plt.grid(True)
        plt.show()
else:
    print('Imports successful. To run pipeline, set RUN_PIPELINE = True in this cell.')

[DEBUG] ReserveFeatureBuilder.build: incoming columns=['予約日', '予約得意先名', '固定客', '予約台数']
[DEBUG] ReserveFeatureBuilder.build: sample rows=
{'予約日': [Timestamp('2023-01-04 00:00:00'), Timestamp('2023-01-04 00:00:00'), Timestamp('2023-01-04 00:00:00')], '予約得意先名': ['アンデス', 'リサイクルレスキュー', '山口興業'], '固定客': [False, False, False], '予約台数': [1.0, 1.0, 2.0]}
[DEBUG] reservation_filtered_days= 761
[DEBUG] reservation_span= 2023-01-04 00:00:00 -> 2025-05-26 00:00:00

=== 300日分のデータで評価中 ===
[DEBUG] df_subset_days= 280 range= 2024-07-30 00:00:00 -> 2025-05-26 00:00:00
▶️ full_walkforward 開始
[DEBUG] full_walkforward: df_raw.shape=(47504, 3), holidays_type=<class 'list'> df_reserve.shape=(45731, 4)
[DEBUG] WeightFeatureBuilder.build: past_raw.shape=(47504, 3), target_items=['混合廃棄物A', '混合廃棄物B']
[DEBUG] WeightFeatureBuilder.build: holidays type=<class 'list'>, len_or_none=20
[DEBUG] WeightFeatureBuilder.build: df_pivot.shape=(280, 226), df_feat.shape=(280, 17)
[DEBUG] ReserveFeatureBuilder.build: incoming columns=['予約日', '予約得意先名', '固定客', '予約台数']
[DEBUG] ReserveFeatureBuilder.build: sample rows=
{'予約日': [Timestamp('2023-01-04 00:00:00'), Timestamp('2023-01-04 00:00:00'), Timestamp('2023-01-04 00:00:00')], '予約得意先名': ['アンデス', 'リサイクルレスキュー', '山口興業'], '固定客': [False, False, False], '予約台数': [1.0, 1.0, 2.0]}
[DEBUG] reservation_filtered_days= 761
[DEBUG] reservation_span= 2023-01-04 00:00:00 -> 2025-05-26 00:00:00

=== 300日分のデータで評価中 ===
[DEBUG] df_subset_days= 280 range= 2024-07-30 00:00:00 -> 2025-05-26 00:00:00
▶️ full_walkforward 開始
[DEBUG] full_walkforward: df_raw.shape=(47504, 3), holidays_type=<class 'list'> df_reserve.shape=(45731, 4)
[DEBUG] WeightFeatureBuilder.build: past_raw.shape=(47504, 3), target_items=['混合廃棄物A', '混合廃棄物B']
[DEBUG] WeightFeatureBuilder.build: holidays type=<class 'list'>, len_or_none=20
[DEBUG] WeightFeatureBuilder.build: df_pivot.shape=(280, 226), df_feat.shape=(280, 17)
[DEBUG] ReserveFeatureBuilder.build: incoming columns=['予約日', '予約得意先名', '固定客', '予約台数']
[DEBUG] ReserveFeatureBuilder.build: sample rows=
{'予約日': [Timestamp('2023-01-04 00:00:00'), Timestamp('2023-01-04 00:00:00'), Timestamp('2023-01-04 00:00:00')], '予約得意先名': ['アンデス', 'リサイクルレスキュー', '山口興業'], '固定客': [False, False, False], '予約台数': [1.0, 1.0, 2.0]}
[DEBUG] full_walkforward: dates_len=270 min_stage1_days=20 min_stage2_days=10 -> required_min_predictions=31

=== 2024-09-01 を予測中 ===
[DEBUG] iteration i=20: df_past_feat.shape=(20, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(20, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
[DEBUG] full_walkforward: dates_len=270 min_stage1_days=20 min_stage2_days=10 -> required_min_predictions=31

=== 2024-09-01 を予測中 ===
[DEBUG] iteration i=20: df_past_feat.shape=(20, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(20, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
[DEBUG] ステージ2未実行: all_stage1_rows=1 / 閾値>10

=== 2024-09-02 を予測中 ===
[DEBUG] iteration i=21: df_past_feat.shape=(21, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(21, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
[DEBUG] ステージ2未実行: all_stage1_rows=1 / 閾値>10

=== 2024-09-02 を予測中 ===
[DEBUG] iteration i=21: df_past_feat.shape=(21, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(21, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
[DEBUG] ステージ2未実行: all_stage1_rows=2 / 閾値>10
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
[DEBUG] ステージ2未実行: all_stage1_rows=2 / 閾値>10

=== 2024-09-03 を予測中 ===
[DEBUG] iteration i=22: df_past_feat.shape=(22, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(22, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A

=== 2024-09-03 を予測中 ===
[DEBUG] iteration i=22: df_past_feat.shape=(22, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(22, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
[DEBUG] ステージ2未実行: all_stage1_rows=3 / 閾値>10

=== 2024-09-04 を予測中 ===
[DEBUG] iteration i=23: df_past_feat.shape=(23, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(23, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
[DEBUG] ステージ2未実行: all_stage1_rows=3 / 閾値>10

=== 2024-09-04 を予測中 ===
[DEBUG] iteration i=23: df_past_feat.shape=(23, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(23, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
[DEBUG] ステージ2未実行: all_stage1_rows=4 / 閾値>10

=== 2024-09-05 を予測中 ===
[DEBUG] iteration i=24: df_past_feat.shape=(24, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(24, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
[DEBUG] ステージ2未実行: all_stage1_rows=4 / 閾値>10

=== 2024-09-05 を予測中 ===
[DEBUG] iteration i=24: df_past_feat.shape=(24, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(24, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
[DEBUG] ステージ2未実行: all_stage1_rows=5 / 閾値>10

=== 2024-09-06 を予測中 ===
[DEBUG] iteration i=25: df_past_feat.shape=(25, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(25, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
[DEBUG] ステージ2未実行: all_stage1_rows=5 / 閾値>10

=== 2024-09-06 を予測中 ===
[DEBUG] iteration i=25: df_past_feat.shape=(25, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(25, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B

=== 2024-09-07 を予測中 ===
[DEBUG] iteration i=26: df_past_feat.shape=(26, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(26, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B

=== 2024-09-07 を予測中 ===
[DEBUG] iteration i=26: df_past_feat.shape=(26, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(26, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B

=== 2024-09-09 を予測中 ===
[DEBUG] iteration i=27: df_past_feat.shape=(27, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(27, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物B

=== 2024-09-09 を予測中 ===
[DEBUG] iteration i=27: df_past_feat.shape=(27, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(27, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B

=== 2024-09-10 を予測中 ===
[DEBUG] iteration i=28: df_past_feat.shape=(28, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(28, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A

=== 2024-09-10 を予測中 ===
[DEBUG] iteration i=28: df_past_feat.shape=(28, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(28, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B

=== 2024-09-11 を予測中 ===
[DEBUG] iteration i=29: df_past_feat.shape=(29, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(29, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B

=== 2024-09-11 を予測中 ===
[DEBUG] iteration i=29: df_past_feat.shape=(29, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(29, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
[DEBUG] ステージ2未実行: all_stage1_rows=10 / 閾値>10

=== 2024-09-12 を予測中 ===
[DEBUG] iteration i=30: df_past_feat.shape=(30, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(30, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
[DEBUG] ステージ2未実行: all_stage1_rows=10 / 閾値>10

=== 2024-09-12 を予測中 ===
[DEBUG] iteration i=30: df_past_feat.shape=(30, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(30, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B

▶️ train_and_predict_stage2 開始
[DEBUG] train_and_predict_stage2: all_stage1_rows_count=11 sample_keys=['混合廃棄物A_予測', '混合廃棄物B_予測', '混合廃棄物A_前日値', '混合廃棄物A_前週平均', '混合廃棄物B_前日値', '混合廃棄物B_前週平均', '合計_前日値', '合計_3日平均']
✅ 合計予測: 56829.7kg
[DEBUG] ランニング指標計算失敗: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 3) + inhomogeneous part.

=== 2024-09-13 を予測中 ===
[DEBUG] iteration i=31: df_past_feat.shape=(31, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(31, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A

▶️ train_and_predict_stage2 開始
[DEBUG] train_and_predict_stage2: all_stage1_rows_count=11 sample_keys=['混合廃棄物A_予測', '混合廃棄物B_予測', '混合廃棄物A_前日値', '混合廃棄物A_前週平均', '混合廃棄物B_前日値', '混合廃棄物B_前週平均', '合計_前日値', '合計_3日平均']
✅ 合計予測: 56829.7kg
[DEBUG] ランニング指標計算失敗: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (1, 3) + inhomogeneous part.

=== 2024-09-13 を予測中 ===
[DEBUG] iteration i=31: df_past_feat.shape=(31, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(31, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B

▶️ train_and_predict_stage2 開始
[DEBUG] train_and_predict_stage2: all_stage1_rows_count=12 sample_keys=['混合廃棄物A_予測', '混合廃棄物B_予測', '混合廃棄物A_前日値', '混合廃棄物A_前週平均', '混合廃棄物B_前日値', '混合廃棄物B_前週平均', '合計_前日値', '合計_3日平均']
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B

▶️ train_and_predict_stage2 開始
[DEBUG] train_and_predict_stage2: all_stage1_rows_count=12 sample_keys=['混合廃棄物A_予測', '混合廃棄物B_予測', '混合廃棄物A_前日値', '混合廃棄物A_前週平均', '混合廃棄物B_前日値', '混合廃棄物B_前週平均', '合計_前日値', '合計_3日平均']
✅ 合計予測: 60648.5kg
[DEBUG] ランニング指標計算失敗: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 3) + inhomogeneous part.

=== 2024-09-14 を予測中 ===
[DEBUG] iteration i=32: df_past_feat.shape=(32, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(32, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
✅ 合計予測: 60648.5kg
[DEBUG] ランニング指標計算失敗: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 3) + inhomogeneous part.

=== 2024-09-14 を予測中 ===
[DEBUG] iteration i=32: df_past_feat.shape=(32, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(32, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B

▶️ train_and_predict_stage2 開始
[DEBUG] train_and_predict_stage2: all_stage1_rows_count=13 sample_keys=['混合廃棄物A_予測', '混合廃棄物B_予測', '混合廃棄物A_前日値', '混合廃棄物A_前週平均', '混合廃棄物B_前日値', '混合廃棄物B_前週平均', '合計_前日値', '合計_3日平均']
✅ 合計予測: 46902.4kg
[DEBUG] ランニング指標計算失敗: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 3) + inhomogeneous part.

=== 2024-09-15 を予測中 ===
[DEBUG] iteration i=33: df_past_feat.shape=(33, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(33, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']

▶️ train_and_predict_stage2 開始
[DEBUG] train_and_predict_stage2: all_stage1_rows_count=13 sample_keys=['混合廃棄物A_予測', '混合廃棄物B_予測', '混合廃棄物A_前日値', '混合廃棄物A_前週平均', '混合廃棄物B_前日値', '混合廃棄物B_前週平均', '合計_前日値', '合計_3日平均']
✅ 合計予測: 46902.4kg
[DEBUG] ランニング指標計算失敗: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 3) + inhomogeneous part.

=== 2024-09-15 を予測中 ===
[DEBUG] iteration i=33: df_past_feat.shape=(33, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(33, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B

▶️ train_and_predict_stage2 開始
[DEBUG] train_and_predict_stage2: all_stage1_rows_count=14 sample_keys=['混合廃棄物A_予測', '混合廃棄物B_予測', '混合廃棄物A_前日値', '混合廃棄物A_前週平均', '混合廃棄物B_前日値', '混合廃棄物B_前週平均', '合計_前日値', '合計_3日平均']
✅ 合計予測: 29948.3kg
[DEBUG] ランニング指標計算失敗: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (4, 3) + inhomogeneous part.

=== 2024-09-16 を予測中 ===
[DEBUG] iteration i=34: df_past_feat.shape=(34, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(34, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A

▶️ train_and_predict_stage2 開始
[DEBUG] train_and_predict_stage2: all_stage1_rows_count=14 sample_keys=['混合廃棄物A_予測', '混合廃棄物B_予測', '混合廃棄物A_前日値', '混合廃棄物A_前週平均', '混合廃棄物B_前日値', '混合廃棄物B_前週平均', '合計_前日値', '合計_3日平均']
✅ 合計予測: 29948.3kg
[DEBUG] ランニング指標計算失敗: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (4, 3) + inhomogeneous part.

=== 2024-09-16 を予測中 ===
[DEBUG] iteration i=34: df_past_feat.shape=(34, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(34, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B

▶️ train_and_predict_stage2 開始
[DEBUG] train_and_predict_stage2: all_stage1_rows_count=15 sample_keys=['混合廃棄物A_予測', '混合廃棄物B_予測', '混合廃棄物A_前日値', '混合廃棄物A_前週平均', '混合廃棄物B_前日値', '混合廃棄物B_前週平均', '合計_前日値', '合計_3日平均']
✅ 合計予測: 41281.7kg
[DEBUG] ランニング指標計算失敗: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (5, 3) + inhomogeneous part.

=== 2024-09-17 を予測中 ===
[DEBUG] iteration i=35: df_past_feat.shape=(35, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(35, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A

▶️ train_and_predict_stage2 開始
[DEBUG] train_and_predict_stage2: all_stage1_rows_count=15 sample_keys=['混合廃棄物A_予測', '混合廃棄物B_予測', '混合廃棄物A_前日値', '混合廃棄物A_前週平均', '混合廃棄物B_前日値', '混合廃棄物B_前週平均', '合計_前日値', '合計_3日平均']
✅ 合計予測: 41281.7kg
[DEBUG] ランニング指標計算失敗: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (5, 3) + inhomogeneous part.

=== 2024-09-17 を予測中 ===
[DEBUG] iteration i=35: df_past_feat.shape=(35, 24), df_feat_today.shape=(1, 24)

▶️ train_and_predict_stage1 開始
[DEBUG] train_and_predict_stage1: X_train.shape=(35, 20), df_past_pivot_cols=['Cﾌﾟﾚｽ', 'GA H鋼･鉄筋等', 'GB', 'GC 軽鉄･ｽﾁｰﾙ類', 'GC\u3000軽鉄・ｽﾁｰﾙ類']
🛠 モデル訓練中: elastic for 混合廃棄物A
🛠 モデル訓練中: rf for 混合廃棄物A
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B

▶️ train_and_predict_stage2 開始
[DEBUG] train_and_predict_stage2: all_stage1_rows_count=16 sample_keys=['混合廃棄物A_予測', '混合廃棄物B_予測', '混合廃棄物A_前日値', '混合廃棄物A_前週平均', '混合廃棄物B_前日値', '混合廃棄物B_前週平均', '合計_前日値', '合計_3日平均']
🛠 モデル訓練中: elastic for 混合廃棄物B
🛠 モデル訓練中: rf for 混合廃棄物B

▶️ train_and_predict_stage2 開始
[DEBUG] train_and_predict_stage2: all_stage1_rows_count=16 sample_keys=['混合廃棄物A_予測', '混合廃棄物B_予測', '混合廃棄物A_前日値', '混合廃棄物A_前週平均', '混合廃棄物B_前日値', '混合廃棄物B_前週平均', '合計_前日値', '合計_3日平均']
✅ 合計予測: 57649.6kg

## 天気追加モデル

In [9]:
# new_model2: PRE_HANNNYU/scripts/new_model2 内のローカルモジュール利用 (再読込対応)
import sys, os, importlib
SCRIPT_ROOT = "/works/scripts"
if SCRIPT_ROOT not in sys.path:
    sys.path.append(SCRIPT_ROOT)
# 既存モジュールを再読込して最新パッチ反映
import new_model2.feature_builder as nm2_fb
import new_model2.predict_model_v4_2_4 as nm2_pred
importlib.reload(nm2_fb)
importlib.reload(nm2_pred)
from new_model2.predict_model_v4_2_4 import full_walkforward
from new_model2.feature_builder import WeatherFeatureBuilder, ReserveFeatureBuilder
from sklearn.metrics import r2_score, mean_absolute_error
import pandas as pd
import matplotlib.pyplot as plt

print('[INFO] using WeatherFeatureBuilder from', WeatherFeatureBuilder.__module__)

# 予約 raw データは df_reserve として既に存在 (列: 予約日, 予約得意先名, 固定客, 予約台数)
# 集計済み特徴量はここでは不要なので生成しない（full_walkforward 内で再度 ReserveFeatureBuilder を用いるため）
if not pd.api.types.is_datetime64_any_dtype(df_reserve['予約日']):
    df_reserve['予約日'] = pd.to_datetime(df_reserve['予約日'])

# 日付型保証
if not pd.api.types.is_datetime64_any_dtype(df_all["伝票日付"]):
    df_all["伝票日付"] = pd.to_datetime(df_all["伝票日付"])

# 評価対象の日数リスト
days_list = [90,180,360,720]  # 検証を速くするため一旦 1 パターン
results = []

for days in days_list:
    print(f"\n=== {days}日分のデータで評価中 (weather) ===")
    latest_date = df_all["伝票日付"].max()
    cutoff_date = latest_date - pd.Timedelta(days=days)
    df_subset = df_all[df_all["伝票日付"] >= cutoff_date].copy()
    hol_min = df_subset["伝票日付"].min()
    hol_max = df_subset["伝票日付"].max()
    print('[DEBUG] hol_min, hol_max =', hol_min, hol_max)
    holidays = get_japanese_holidays(hol_min, hol_max)

    # 予約 raw サブセット（列 予約日 でフィルタ）
    mask = (df_reserve['予約日'] >= hol_min) & (df_reserve['予約日'] <= hol_max)
    df_reserve_raw_subset = df_reserve.loc[mask].copy()
    print(f"[DEBUG] reserve_raw_rows={len(df_reserve_raw_subset)} range={df_reserve_raw_subset['予約日'].min()}->{df_reserve_raw_subset['予約日'].max() if len(df_reserve_raw_subset) else 'NA'}")

    # 天気特徴量取得
    weather_builder = WeatherFeatureBuilder(start_date=hol_min, end_date=hol_max, enable_fallback=True)
    df_weather_full = weather_builder.build()
    df_weather = df_weather_full.loc[hol_min:hol_max].copy() if not df_weather_full.empty else df_weather_full
    if len(df_weather) > 0:
        print(f"[DEBUG] weather_rows={len(df_weather)} range={df_weather.index.min()}->{df_weather.index.max()}")
    else:
        print("[DEBUG] weather empty (fallback or no data)")

    try:
        actual, pred = full_walkforward(
            df_raw=df_subset,
            df_reserve=df_reserve_raw_subset,  # 修正: raw を渡す
            holidays=holidays,
            df_weather=df_weather,
            min_stage1_days=30,
            min_stage2_days=15,
            top_n=2,
        )
        print(f"[DEBUG] returned_lengths actual={len(actual) if isinstance(actual,list) else 'NA'} pred={len(pred) if isinstance(pred,list) else 'NA'}")
        if isinstance(actual, list) and isinstance(pred, list) and len(actual) > 0 and len(pred) > 0:
            r2 = r2_score(actual, pred)
            mae = mean_absolute_error(actual, pred)
            results.append((days, r2, mae))
            print(f"✅ R² = {r2:.3f}, MAE = {mae:,.0f}kg")
        else:
            print("⚠ 評価に十分なデータがありません (予測件数0)")
            results.append((days, None, None))
    except Exception as e:
        print(f"❌ エラー: {e}")
        results.append((days, None, None))

# 結果表示
import pandas as pd

df_result = pd.DataFrame(results, columns=["days", "R2", "MAE"])
print("\n=== 評価結果 (new_model2) ===")
print(df_result)
if df_result["R2"].notna().any():
    plt.plot(df_result["days"], df_result["R2"], marker="o")
    plt.xlabel("Days")
    plt.ylabel("R² Score")
    plt.title("日数別 R² 評価 (new_model2)")
    plt.grid(True)
    plt.show()
else:
    print("R² 有効値が無いためプロットをスキップ")

[INFO] using WeatherFeatureBuilder from new_model2.feature_builder

=== 90日分のデータで評価中 (weather) ===
[DEBUG] hol_min, hol_max = 2025-02-25 00:00:00 2025-05-26 00:00:00
[DEBUG] reserve_raw_rows=4773 range=2025-02-25 00:00:00->2025-05-26 00:00:00
[Weather] fetch 2025-02-25 -> 2025-05-26
[Weather] final params start_date=2025-02-25 end_date=2025-05-26
[Weather] status=200 url=https://archive-api.open-meteo.com/v1/archive?latitude=35.6895&longitude=139.6917&start_date=2025-02-25&end_date=2025-05-26&daily=temperature_2m_mean&daily=precipitation_sum&timezone=Asia%2FTokyo
[Weather] rows=91 cols=['平均気温', '降水量', '天気_大雨', '天気_晴れ', '天気_雨', '天気_台風']
[DEBUG] weather_rows=91 range=2025-02-25 00:00:00->2025-05-26 00:00:00
▶️ full_walkforward(new_model2) 開始
[DEBUG] target_items=['混合廃棄物A', '混合廃棄物B']
[DEBUG] feature_list_len=23 (orig=23) df_feat_rows=74
[DEBUG] dates_len=74 min_stage1_days=30 min_stage2_days=15
[SKIP] 2025-03-07 (i=0) < min_stage1_days=30
[SKIP] 2025-03-13 (i=5) < min_stage1_days=30
[SKIP] 2025-03-18 (i=10) < min_stage1_days=30
[SKIP] 2025-03-23 (i=15) < min_stage1_days=30
[SKIP] 2025-03-28 (i=20) < min_stage1_days=30
[SKIP] 2025-04-02 (i=25) < min_stage1_days=30

=== 2025-04-07 を予測中 (i=30) ===
[Weather] status=200 url=https://archive-api.open-meteo.com/v1/archive?latitude=35.6895&longitude=139.6917&start_date=2025-02-25&end_date=2025-05-26&daily=temperature_2m_mean&daily=precipitation_sum&timezone=Asia%2FTokyo
[Weather] rows=91 cols=['平均気温', '降水量', '天気_大雨', '天気_晴れ', '天気_雨', '天気_台風']
[DEBUG] weather_rows=91 range=2025-02-25 00:00:00->2025-05-26 00:00:00
▶️ full_walkforward(new_model2) 開始
[DEBUG] target_items=['混合廃棄物A', '混合廃棄物B']
[DEBUG] feature_list_len=23 (orig=23) df_feat_rows=74
[DEBUG] dates_len=74 min_stage1_days=30 min_stage2_days=15
[SKIP] 2025-03-07 (i=0) < min_stage1_days=30
[SKIP] 2025-03-13 (i=5) < min_stage1_days=30
[SKIP] 2025-03-18 (i=10) < min_stage1_days=30
[SKIP] 2025-03-23 (i=15) < min_stage1_days=30
[SKIP] 2025-03-28 (i=20) < min_stage1_days=30
[SKIP] 2025-04-02 (i=25) < min_stage1_days=30

=== 2025-04-07 を予測中 (i=30) ===
[DEBUG] ステージ2未実行 rows=1/16

=== 2025-04-08 を予測中 (i=31) ===
[DEBUG] ステージ2未実行 rows=1/16

=== 2025-04-08 を予測中 (i=31) ===
[DEBUG] ステージ2未実行 rows=2/16

=== 2025-04-09 を予測中 (i=32) ===
[DEBUG] ステージ2未実行 rows=2/16

=== 2025-04-09 を予測中 (i=32) ===
[DEBUG] ステージ2未実行 rows=3/16

=== 2025-04-10 を予測中 (i=33) ===
[DEBUG] ステージ2未実行 rows=3/16

=== 2025-04-10 を予測中 (i=33) ===
[DEBUG] ステージ2未実行 rows=4/16

=== 2025-04-11 を予測中 (i=34) ===
[DEBUG] ステージ2未実行 rows=4/16

=== 2025-04-11 を予測中 (i=34) ===
[DEBUG] ステージ2未実行 rows=5/16

=== 2025-04-12 を予測中 (i=35) ===
[DEBUG] ステージ2未実行 rows=5/16

=== 2025-04-12 を予測中 (i=35) ===
[DEBUG] ステージ2未実行 rows=6/16

=== 2025-04-14 を予測中 (i=36) ===
[DEBUG] ステージ2未実行 rows=6/16

=== 2025-04-14 を予測中 (i=36) ===
[DEBUG] ステージ2未実行 rows=7/16

=== 2025-04-15 を予測中 (i=37) ===
[DEBUG] ステージ2未実行 rows=7/16

=== 2025-04-15 を予測中 (i=37) ===
[DEBUG] ステージ2未実行 rows=8/16

=== 2025-04-16 を予測中 (i=38) ===
[DEBUG] ステージ2未実行 rows=8/16

=== 2025-04-16 を予測中 (i=38) ===
[DEBUG] ステージ2未実行 rows=9/16

=== 2025-04-17 を予測中 (i=39) ===
[DEBUG] ステージ2未実行 rows=9/16

=== 2025-04-17 を予測中 (i=39) ===
[DEBUG] ステージ2未実行 rows=10/16

=== 2025-04-18 を予測中 (i=40) ===
[DEBUG] ステージ2未実行 rows=10/16

=== 2025-04-18 を予測中 (i=40) ===
[DEBUG] ステージ2未実行 rows=11/16

=== 2025-04-19 を予測中 (i=41) ===
[DEBUG] ステージ2未実行 rows=11/16

=== 2025-04-19 を予測中 (i=41) ===
[DEBUG] ステージ2未実行 rows=12/16

=== 2025-04-21 を予測中 (i=42) ===
[DEBUG] ステージ2未実行 rows=12/16

=== 2025-04-21 を予測中 (i=42) ===
[DEBUG] ステージ2未実行 rows=13/16

=== 2025-04-22 を予測中 (i=43) ===
[DEBUG] ステージ2未実行 rows=13/16

=== 2025-04-22 を予測中 (i=43) ===
[DEBUG] ステージ2未実行 rows=14/16

=== 2025-04-23 を予測中 (i=44) ===
[DEBUG] ステージ2未実行 rows=14/16

=== 2025-04-23 を予測中 (i=44) ===
[DEBUG] ステージ2未実行 rows=15/16

=== 2025-04-24 を予測中 (i=45) ===
[DEBUG] ステージ2未実行 rows=15/16

=== 2025-04-24 を予測中 (i=45) ===

=== 2025-04-25 を予測中 (i=46) ===

=== 2025-04-25 を予測中 (i=46) ===

=== 2025-04-26 を予測中 (i=47) ===

=== 2025-04-26 を予測中 (i=47) ===
[PROGRESS] n=3 R²=-1.872 MAE=5,559kg

=== 2025-04-27 を予測中 (i=48) ===
[PROGRESS] n=3 R²=-1.872 MAE=5,559kg

=== 2025-04-27 を予測中 (i=48) ===
[PROGRESS] n=4 R²=-0.719 MAE=16,675kg

=== 2025-04-28 を予測中 (i=49) ===
[PROGRESS] n=4 R²=-0.719 MAE=16,675kg

=== 2025-04-28 を予測中 (i=49) ===
[PROGRESS] n=5 R²=-0.654 MAE=13,587kg

=== 2025-04-29 を予測中 (i=50) ===
[PROGRESS] n=5 R²=-0.654 MAE=13,587kg

=== 2025-04-29 を予測中 (i=50) ===
[PROGRESS] n=6 R²=-0.866 MAE=16,591kg

=== 2025-04-30 を予測中 (i=51) ===
[PROGRESS] n=6 R²=-0.866 MAE=16,591kg

=== 2025-04-30 を予測中 (i=51) ===
[PROGRESS] n=7 R²=-0.723 MAE=14,444kg

=== 2025-05-01 を予測中 (i=52) ===
[PROGRESS] n=7 R²=-0.723 MAE=14,444kg

=== 2025-05-01 を予測中 (i=52) ===
[PROGRESS] n=8 R²=-0.764 MAE=14,113kg

=== 2025-05-02 を予測中 (i=53) ===
[PROGRESS] n=8 R²=-0.764 MAE=14,113kg

=== 2025-05-02 を予測中 (i=53) ===
[PROGRESS] n=9 R²=-0.620 MAE=13,609kg

=== 2025-05-07 を予測中 (i=54) ===
[PROGRESS] n=9 R²=-0.620 MAE=13,609kg

=== 2025-05-07 を予測中 (i=54) ===
[PROGRESS] n=10 R²=-0.464 MAE=14,620kg

=== 2025-05-08 を予測中 (i=55) ===
[PROGRESS] n=10 R²=-0.464 MAE=14,620kg

=== 2025-05-08 を予測中 (i=55) ===
[PROGRESS] n=11 R²=-0.452 MAE=14,707kg

=== 2025-05-09 を予測中 (i=56) ===
[PROGRESS] n=11 R²=-0.452 MAE=14,707kg

=== 2025-05-09 を予測中 (i=56) ===
[PROGRESS] n=12 R²=-0.402 MAE=13,765kg

=== 2025-05-10 を予測中 (i=57) ===
[PROGRESS] n=12 R²=-0.402 MAE=13,765kg

=== 2025-05-10 を予測中 (i=57) ===
[PROGRESS] n=13 R²=-0.474 MAE=14,163kg

=== 2025-05-11 を予測中 (i=58) ===
[PROGRESS] n=13 R²=-0.474 MAE=14,163kg

=== 2025-05-11 を予測中 (i=58) ===
[PROGRESS] n=14 R²=-0.065 MAE=15,265kg

=== 2025-05-12 を予測中 (i=59) ===
[PROGRESS] n=14 R²=-0.065 MAE=15,265kg

=== 2025-05-12 を予測中 (i=59) ===
[PROGRESS] n=15 R²=-0.066 MAE=14,428kg

=== 2025-05-13 を予測中 (i=60) ===
[PROGRESS] n=15 R²=-0.066 MAE=14,428kg

=== 2025-05-13 を予測中 (i=60) ===
[PROGRESS] n=16 R²=-0.043 MAE=13,914kg

=== 2025-05-14 を予測中 (i=61) ===
[PROGRESS] n=16 R²=-0.043 MAE=13,914kg

=== 2025-05-14 を予測中 (i=61) ===
[PROGRESS] n=17 R²=-0.040 MAE=13,239kg

=== 2025-05-15 を予測中 (i=62) ===
[PROGRESS] n=17 R²=-0.040 MAE=13,239kg

=== 2025-05-15 を予測中 (i=62) ===
[PROGRESS] n=18 R²=-0.057 MAE=13,260kg

=== 2025-05-16 を予測中 (i=63) ===
[PROGRESS] n=18 R²=-0.057 MAE=13,260kg

=== 2025-05-16 を予測中 (i=63) ===
[PROGRESS] n=19 R²=-0.046 MAE=12,678kg

=== 2025-05-17 を予測中 (i=64) ===
[PROGRESS] n=19 R²=-0.046 MAE=12,678kg

=== 2025-05-17 を予測中 (i=64) ===
[PROGRESS] n=20 R²=-0.060 MAE=12,653kg

=== 2025-05-18 を予測中 (i=65) ===
[PROGRESS] n=20 R²=-0.060 MAE=12,653kg

=== 2025-05-18 を予測中 (i=65) ===
[PROGRESS] n=21 R²=0.152 MAE=12,320kg

=== 2025-05-19 を予測中 (i=66) ===
[PROGRESS] n=21 R²=0.152 MAE=12,320kg

=== 2025-05-19 を予測中 (i=66) ===
[PROGRESS] n=22 R²=0.161 MAE=11,785kg

=== 2025-05-20 を予測中 (i=67) ===
[PROGRESS] n=22 R²=0.161 MAE=11,785kg

=== 2025-05-20 を予測中 (i=67) ===
[PROGRESS] n=23 R²=0.135 MAE=11,954kg

=== 2025-05-21 を予測中 (i=68) ===
[PROGRESS] n=23 R²=0.135 MAE=11,954kg

=== 2025-05-21 を予測中 (i=68) ===
[PROGRESS] n=24 R²=0.143 MAE=11,767kg

=== 2025-05-22 を予測中 (i=69) ===
[PROGRESS] n=24 R²=0.143 MAE=11,767kg

=== 2025-05-22 を予測中 (i=69) ===
[PROGRESS] n=25 R²=0.136 MAE=11,586kg

=== 2025-05-23 を予測中 (i=70) ===
[PROGRESS] n=25 R²=0.136 MAE=11,586kg

=== 2025-05-23 を予測中 (i=70) ===
[PROGRESS] n=26 R²=0.133 MAE=11,338kg

=== 2025-05-24 を予測中 (i=71) ===
[PROGRESS] n=26 R²=0.133 MAE=11,338kg

=== 2025-05-24 を予測中 (i=71) ===
[PROGRESS] n=27 R²=0.133 MAE=10,985kg

=== 2025-05-25 を予測中 (i=72) ===
[PROGRESS] n=27 R²=0.133 MAE=10,985kg

=== 2025-05-25 を予測中 (i=72) ===
[PROGRESS] n=28 R²=0.270 MAE=10,701kg

=== 2025-05-26 を予測中 (i=73) ===
[PROGRESS] n=28 R²=0.270 MAE=10,701kg

=== 2025-05-26 を予測中 (i=73) ===
[PROGRESS] n=29 R²=0.267 MAE=10,566kg

===== ステージ2評価結果 (合計) =====
R² = 0.267, MAE = 10,566kg

===== ステージ1評価結果 =====
混合廃棄物A: R² = 0.623, MAE = 5,344kg
混合廃棄物B: R² = 0.420, MAE = 2,761kg
❌ エラー: too many values to unpack (expected 2)

=== 180日分のデータで評価中 (weather) ===
[DEBUG] hol_min, hol_max = 2024-11-27 00:00:00 2025-05-26 00:00:00
[DEBUG] reserve_raw_rows=9126 range=2024-11-27 00:00:00->2025-05-26 00:00:00
[Weather] fetch 2024-11-27 -> 2025-05-26
[Weather] final params start_date=2024-11-27 end_date=2025-05-26
[PROGRESS] n=29 R²=0.267 MAE=10,566kg

===== ステージ2評価結果 (合計) =====
R² = 0.267, MAE = 10,566kg

===== ステージ1評価結果 =====
混合廃棄物A: R² = 0.623, MAE = 5,344kg
混合廃棄物B: R² = 0.420, MAE = 2,761kg
❌ エラー: too many values to unpack (expected 2)

=== 180日分のデータで評価中 (weather) ===
[DEBUG] hol_min, hol_max = 2024-11-27 00:00:00 2025-05-26 00:00:00
[DEBUG] reserve_raw_rows=9126 range=2024-11-27 00:00:00->2025-05-26 00:00:00
[Weather] fetch 2024-11-27 -> 2025-05-26
[Weather] final params start_date=2024-11-27 end_date=2025-05-26
[Weather] status=200 url=https://archive-api.open-meteo.com/v1/archive?latitude=35.6895&longitude=139.6917&start_date=2024-11-27&end_date=2025-05-26&daily=temperature_2m_mean&daily=precipitation_sum&timezone=Asia%2FTokyo
[Weather] rows=181 cols=['平均気温', '降水量', '天気_大雨', '天気_晴れ', '天気_雨', '天気_台風']
[DEBUG] weather_rows=181 range=2024-11-27 00:00:00->2025-05-26 00:00:00
▶️ full_walkforward(new_model2) 開始
[DEBUG] target_items=['混合廃棄物A', '混合廃棄物B']
[Weather] status=200 url=https://archive-api.open-meteo.com/v1/archive?latitude=35.6895&longitude=139.6917&start_date=2024-11-27&end_date=2025-05-26&daily=temperature_2m_mean&daily=precipitation_sum&timezone=Asia%2FTokyo
[Weather] rows=181 cols=['平均気温', '降水量', '天気_大雨', '天気_晴れ', '天気_雨', '天気_台風']
[DEBUG] weather_rows=181 range=2024-11-27 00:00:00->2025-05-26 00:00:00
▶️ full_walkforward(new_model2) 開始
[DEBUG] target_items=['混合廃棄物A', '混合廃棄物B']
[DEBUG] feature_list_len=23 (orig=23) df_feat_rows=156
[DEBUG] dates_len=156 min_stage1_days=30 min_stage2_days=15
[SKIP] 2024-12-07 (i=0) < min_stage1_days=30
[SKIP] 2024-12-12 (i=5) < min_stage1_days=30
[SKIP] 2024-12-17 (i=10) < min_stage1_days=30
[SKIP] 2024-12-22 (i=15) < min_stage1_days=30
[SKIP] 2024-12-27 (i=20) < min_stage1_days=30
[SKIP] 2025-01-09 (i=25) < min_stage1_days=30

=== 2025-01-14 を予測中 (i=30) ===
[DEBUG] feature_list_len=23 (orig=23) df_feat_rows=156
[DEBUG] dates_len=156 min_stage1_days=30 min_stage2_days=15
[SKIP] 2024-12-07 (i=0) < min_stage1_days=30
[SKIP] 2024-12-12 (i=5) < min_stage1_days=30
[SKIP] 2024-12-17 (i=10) < min_stage1_days=30
[SKIP] 2024-12-22 (i=15) < min_stage1_days=30
[SKIP] 2024-12-27 (i=20) < min_stage1_days=30
[SKIP] 2025-01-09 (i=25) < min_stage1_days=30

=== 2025-01-14 を予測中 (i=30) ===
[DEBUG] ステージ2未実行 rows=1/16

=== 2025-01-15 を予測中 (i=31) ===
[DEBUG] ステージ2未実行 rows=1/16

=== 2025-01-15 を予測中 (i=31) ===
[DEBUG] ステージ2未実行 rows=2/16

=== 2025-01-16 を予測中 (i=32) ===
[DEBUG] ステージ2未実行 rows=2/16

=== 2025-01-16 を予測中 (i=32) ===
[DEBUG] ステージ2未実行 rows=3/16

=== 2025-01-17 を予測中 (i=33) ===
[DEBUG] ステージ2未実行 rows=3/16

=== 2025-01-17 を予測中 (i=33) ===
[DEBUG] ステージ2未実行 rows=4/16

=== 2025-01-18 を予測中 (i=34) ===
[DEBUG] ステージ2未実行 rows=4/16

=== 2025-01-18 を予測中 (i=34) ===
[DEBUG] ステージ2未実行 rows=5/16

=== 2025-01-19 を予測中 (i=35) ===
[DEBUG] ステージ2未実行 rows=5/16

=== 2025-01-19 を予測中 (i=35) ===
[DEBUG] ステージ2未実行 rows=6/16

=== 2025-01-20 を予測中 (i=36) ===
[DEBUG] ステージ2未実行 rows=6/16

=== 2025-01-20 を予測中 (i=36) ===
[DEBUG] ステージ2未実行 rows=7/16

=== 2025-01-21 を予測中 (i=37) ===
[DEBUG] ステージ2未実行 rows=7/16

=== 2025-01-21 を予測中 (i=37) ===
[DEBUG] ステージ2未実行 rows=8/16

=== 2025-01-22 を予測中 (i=38) ===
[DEBUG] ステージ2未実行 rows=8/16

=== 2025-01-22 を予測中 (i=38) ===
[DEBUG] ステージ2未実行 rows=9/16

=== 2025-01-23 を予測中 (i=39) ===
[DEBUG] ステージ2未実行 rows=9/16

=== 2025-01-23 を予測中 (i=39) ===
[DEBUG] ステージ2未実行 rows=10/16

=== 2025-01-24 を予測中 (i=40) ===
[DEBUG] ステージ2未実行 rows=10/16

=== 2025-01-24 を予測中 (i=40) ===
[DEBUG] ステージ2未実行 rows=11/16

=== 2025-01-25 を予測中 (i=41) ===
[DEBUG] ステージ2未実行 rows=11/16

=== 2025-01-25 を予測中 (i=41) ===
[DEBUG] ステージ2未実行 rows=12/16

=== 2025-01-26 を予測中 (i=42) ===
[DEBUG] ステージ2未実行 rows=12/16

=== 2025-01-26 を予測中 (i=42) ===
[DEBUG] ステージ2未実行 rows=13/16

=== 2025-01-27 を予測中 (i=43) ===
[DEBUG] ステージ2未実行 rows=13/16

=== 2025-01-27 を予測中 (i=43) ===
[DEBUG] ステージ2未実行 rows=14/16

=== 2025-01-28 を予測中 (i=44) ===
[DEBUG] ステージ2未実行 rows=14/16

=== 2025-01-28 を予測中 (i=44) ===
[DEBUG] ステージ2未実行 rows=15/16

=== 2025-01-29 を予測中 (i=45) ===
[DEBUG] ステージ2未実行 rows=15/16

=== 2025-01-29 を予測中 (i=45) ===

=== 2025-01-30 を予測中 (i=46) ===

=== 2025-01-30 を予測中 (i=46) ===

=== 2025-01-31 を予測中 (i=47) ===

=== 2025-01-31 を予測中 (i=47) ===
[PROGRESS] n=3 R²=-1.040 MAE=10,316kg

=== 2025-02-01 を予測中 (i=48) ===
[PROGRESS] n=3 R²=-1.040 MAE=10,316kg

=== 2025-02-01 を予測中 (i=48) ===
[PROGRESS] n=4 R²=-1.232 MAE=9,475kg

=== 2025-02-02 を予測中 (i=49) ===
[PROGRESS] n=4 R²=-1.232 MAE=9,475kg

=== 2025-02-02 を予測中 (i=49) ===
[PROGRESS] n=5 R²=0.635 MAE=8,671kg

=== 2025-02-03 を予測中 (i=50) ===
[PROGRESS] n=5 R²=0.635 MAE=8,671kg

=== 2025-02-03 を予測中 (i=50) ===
[PROGRESS] n=6 R²=0.611 MAE=8,230kg

=== 2025-02-04 を予測中 (i=51) ===
[PROGRESS] n=6 R²=0.611 MAE=8,230kg

=== 2025-02-04 を予測中 (i=51) ===
[PROGRESS] n=7 R²=0.433 MAE=9,387kg

=== 2025-02-05 を予測中 (i=52) ===
[PROGRESS] n=7 R²=0.433 MAE=9,387kg

=== 2025-02-05 を予測中 (i=52) ===
[PROGRESS] n=8 R²=0.417 MAE=9,371kg

=== 2025-02-06 を予測中 (i=53) ===
[PROGRESS] n=8 R²=0.417 MAE=9,371kg

=== 2025-02-06 を予測中 (i=53) ===
[PROGRESS] n=9 R²=0.421 MAE=8,343kg

=== 2025-02-07 を予測中 (i=54) ===
[PROGRESS] n=9 R²=0.421 MAE=8,343kg

=== 2025-02-07 を予測中 (i=54) ===
[PROGRESS] n=10 R²=0.345 MAE=8,686kg

=== 2025-02-08 を予測中 (i=55) ===
[PROGRESS] n=10 R²=0.345 MAE=8,686kg

=== 2025-02-08 を予測中 (i=55) ===
[PROGRESS] n=11 R²=0.350 MAE=7,897kg

=== 2025-02-09 を予測中 (i=56) ===
[PROGRESS] n=11 R²=0.350 MAE=7,897kg

=== 2025-02-09 を予測中 (i=56) ===
[PROGRESS] n=12 R²=0.515 MAE=7,585kg

=== 2025-02-10 を予測中 (i=57) ===
[PROGRESS] n=12 R²=0.515 MAE=7,585kg

=== 2025-02-10 を予測中 (i=57) ===
[PROGRESS] n=13 R²=0.522 MAE=7,781kg

=== 2025-02-11 を予測中 (i=58) ===
[PROGRESS] n=13 R²=0.522 MAE=7,781kg

=== 2025-02-11 を予測中 (i=58) ===
[PROGRESS] n=14 R²=0.521 MAE=8,125kg

=== 2025-02-12 を予測中 (i=59) ===
[PROGRESS] n=14 R²=0.521 MAE=8,125kg

=== 2025-02-12 を予測中 (i=59) ===
[PROGRESS] n=15 R²=0.507 MAE=8,181kg

=== 2025-02-13 を予測中 (i=60) ===
[PROGRESS] n=15 R²=0.507 MAE=8,181kg

=== 2025-02-13 を予測中 (i=60) ===
[PROGRESS] n=16 R²=0.499 MAE=8,120kg

=== 2025-02-14 を予測中 (i=61) ===
[PROGRESS] n=16 R²=0.499 MAE=8,120kg

=== 2025-02-14 を予測中 (i=61) ===
[PROGRESS] n=17 R²=0.521 MAE=8,188kg

=== 2025-02-15 を予測中 (i=62) ===
[PROGRESS] n=17 R²=0.521 MAE=8,188kg

=== 2025-02-15 を予測中 (i=62) ===
[PROGRESS] n=18 R²=0.530 MAE=7,856kg

=== 2025-02-16 を予測中 (i=63) ===
[PROGRESS] n=18 R²=0.530 MAE=7,856kg

=== 2025-02-16 を予測中 (i=63) ===
[PROGRESS] n=19 R²=0.618 MAE=7,570kg

=== 2025-02-17 を予測中 (i=64) ===
[PROGRESS] n=19 R²=0.618 MAE=7,570kg

=== 2025-02-17 を予測中 (i=64) ===
[PROGRESS] n=20 R²=0.586 MAE=8,115kg

=== 2025-02-18 を予測中 (i=65) ===
[PROGRESS] n=20 R²=0.586 MAE=8,115kg

=== 2025-02-18 を予測中 (i=65) ===
[PROGRESS] n=21 R²=0.594 MAE=8,056kg

=== 2025-02-19 を予測中 (i=66) ===
[PROGRESS] n=21 R²=0.594 MAE=8,056kg

=== 2025-02-19 を予測中 (i=66) ===
[PROGRESS] n=22 R²=0.604 MAE=7,715kg

=== 2025-02-20 を予測中 (i=67) ===
[PROGRESS] n=22 R²=0.604 MAE=7,715kg

=== 2025-02-20 を予測中 (i=67) ===
[PROGRESS] n=23 R²=0.617 MAE=7,657kg

=== 2025-02-21 を予測中 (i=68) ===
[PROGRESS] n=23 R²=0.617 MAE=7,657kg

=== 2025-02-21 を予測中 (i=68) ===
[PROGRESS] n=24 R²=0.624 MAE=7,484kg

=== 2025-02-22 を予測中 (i=69) ===
[PROGRESS] n=24 R²=0.624 MAE=7,484kg

=== 2025-02-22 を予測中 (i=69) ===
[PROGRESS] n=25 R²=0.624 MAE=7,251kg

=== 2025-02-23 を予測中 (i=70) ===
[PROGRESS] n=25 R²=0.624 MAE=7,251kg

=== 2025-02-23 を予測中 (i=70) ===
[PROGRESS] n=26 R²=0.681 MAE=7,098kg

=== 2025-02-24 を予測中 (i=71) ===
[PROGRESS] n=26 R²=0.681 MAE=7,098kg

=== 2025-02-24 を予測中 (i=71) ===
[PROGRESS] n=27 R²=0.643 MAE=7,490kg

=== 2025-02-25 を予測中 (i=72) ===
[PROGRESS] n=27 R²=0.643 MAE=7,490kg

=== 2025-02-25 を予測中 (i=72) ===
[PROGRESS] n=28 R²=0.643 MAE=7,611kg

=== 2025-02-26 を予測中 (i=73) ===
[PROGRESS] n=28 R²=0.643 MAE=7,611kg

=== 2025-02-26 を予測中 (i=73) ===
[PROGRESS] n=29 R²=0.647 MAE=7,522kg

=== 2025-02-27 を予測中 (i=74) ===
[PROGRESS] n=29 R²=0.647 MAE=7,522kg

=== 2025-02-27 を予測中 (i=74) ===
[PROGRESS] n=30 R²=0.631 MAE=7,629kg

=== 2025-02-28 を予測中 (i=75) ===
[PROGRESS] n=30 R²=0.631 MAE=7,629kg

=== 2025-02-28 を予測中 (i=75) ===
[PROGRESS] n=31 R²=0.624 MAE=7,615kg

=== 2025-03-01 を予測中 (i=76) ===
[PROGRESS] n=31 R²=0.624 MAE=7,615kg

=== 2025-03-01 を予測中 (i=76) ===
[PROGRESS] n=32 R²=0.561 MAE=8,070kg

=== 2025-03-02 を予測中 (i=77) ===
[PROGRESS] n=32 R²=0.561 MAE=8,070kg

=== 2025-03-02 を予測中 (i=77) ===
[PROGRESS] n=33 R²=0.581 MAE=8,051kg

=== 2025-03-03 を予測中 (i=78) ===
[PROGRESS] n=33 R²=0.581 MAE=8,051kg

=== 2025-03-03 を予測中 (i=78) ===
[PROGRESS] n=34 R²=0.586 MAE=7,914kg

=== 2025-03-04 を予測中 (i=79) ===
[PROGRESS] n=34 R²=0.586 MAE=7,914kg

=== 2025-03-04 を予測中 (i=79) ===
[PROGRESS] n=35 R²=0.589 MAE=7,717kg

=== 2025-03-05 を予測中 (i=80) ===
[PROGRESS] n=35 R²=0.589 MAE=7,717kg

=== 2025-03-05 を予測中 (i=80) ===
[PROGRESS] n=36 R²=0.593 MAE=7,528kg

=== 2025-03-06 を予測中 (i=81) ===
[PROGRESS] n=36 R²=0.593 MAE=7,528kg

=== 2025-03-06 を予測中 (i=81) ===
[PROGRESS] n=37 R²=0.596 MAE=7,502kg

=== 2025-03-07 を予測中 (i=82) ===
[PROGRESS] n=37 R²=0.596 MAE=7,502kg

=== 2025-03-07 を予測中 (i=82) ===
[PROGRESS] n=38 R²=0.599 MAE=7,525kg

=== 2025-03-08 を予測中 (i=83) ===
[PROGRESS] n=38 R²=0.599 MAE=7,525kg

=== 2025-03-08 を予測中 (i=83) ===
[PROGRESS] n=39 R²=0.599 MAE=7,618kg

=== 2025-03-10 を予測中 (i=84) ===
[PROGRESS] n=39 R²=0.599 MAE=7,618kg

=== 2025-03-10 を予測中 (i=84) ===
[PROGRESS] n=40 R²=0.603 MAE=7,438kg

=== 2025-03-11 を予測中 (i=85) ===
[PROGRESS] n=40 R²=0.603 MAE=7,438kg

=== 2025-03-11 を予測中 (i=85) ===
[PROGRESS] n=41 R²=0.614 MAE=7,404kg

=== 2025-03-12 を予測中 (i=86) ===
[PROGRESS] n=41 R²=0.614 MAE=7,404kg

=== 2025-03-12 を予測中 (i=86) ===
[PROGRESS] n=42 R²=0.617 MAE=7,247kg

=== 2025-03-13 を予測中 (i=87) ===
[PROGRESS] n=42 R²=0.617 MAE=7,247kg

=== 2025-03-13 を予測中 (i=87) ===
[PROGRESS] n=43 R²=0.619 MAE=7,148kg

=== 2025-03-14 を予測中 (i=88) ===
[PROGRESS] n=43 R²=0.619 MAE=7,148kg

=== 2025-03-14 を予測中 (i=88) ===
[PROGRESS] n=44 R²=0.621 MAE=6,995kg

=== 2025-03-15 を予測中 (i=89) ===
[PROGRESS] n=44 R²=0.621 MAE=6,995kg

=== 2025-03-15 を予測中 (i=89) ===
[PROGRESS] n=45 R²=0.610 MAE=7,066kg

=== 2025-03-16 を予測中 (i=90) ===
[PROGRESS] n=45 R²=0.610 MAE=7,066kg

=== 2025-03-16 を予測中 (i=90) ===
[PROGRESS] n=46 R²=0.647 MAE=6,985kg

=== 2025-03-17 を予測中 (i=91) ===
[PROGRESS] n=46 R²=0.647 MAE=6,985kg

=== 2025-03-17 を予測中 (i=91) ===
[PROGRESS] n=47 R²=0.651 MAE=6,855kg

=== 2025-03-18 を予測中 (i=92) ===
[PROGRESS] n=47 R²=0.651 MAE=6,855kg

=== 2025-03-18 を予測中 (i=92) ===
[PROGRESS] n=48 R²=0.651 MAE=6,777kg

=== 2025-03-19 を予測中 (i=93) ===
[PROGRESS] n=48 R²=0.651 MAE=6,777kg

=== 2025-03-19 を予測中 (i=93) ===
[PROGRESS] n=49 R²=0.651 MAE=6,885kg

=== 2025-03-20 を予測中 (i=94) ===
[PROGRESS] n=49 R²=0.651 MAE=6,885kg

=== 2025-03-20 を予測中 (i=94) ===
[PROGRESS] n=50 R²=0.667 MAE=6,755kg

=== 2025-03-21 を予測中 (i=95) ===
[PROGRESS] n=50 R²=0.667 MAE=6,755kg

=== 2025-03-21 を予測中 (i=95) ===
[PROGRESS] n=51 R²=0.674 MAE=6,689kg

=== 2025-03-22 を予測中 (i=96) ===
[PROGRESS] n=51 R²=0.674 MAE=6,689kg

=== 2025-03-22 を予測中 (i=96) ===
[PROGRESS] n=52 R²=0.666 MAE=6,762kg

=== 2025-03-23 を予測中 (i=97) ===
[PROGRESS] n=52 R²=0.666 MAE=6,762kg

=== 2025-03-23 を予測中 (i=97) ===
[PROGRESS] n=53 R²=0.688 MAE=6,866kg

=== 2025-03-24 を予測中 (i=98) ===
[PROGRESS] n=53 R²=0.688 MAE=6,866kg

=== 2025-03-24 を予測中 (i=98) ===
[PROGRESS] n=54 R²=0.694 MAE=6,844kg

=== 2025-03-25 を予測中 (i=99) ===
[PROGRESS] n=54 R²=0.694 MAE=6,844kg

=== 2025-03-25 を予測中 (i=99) ===
[PROGRESS] n=55 R²=0.684 MAE=7,096kg

=== 2025-03-26 を予測中 (i=100) ===
[PROGRESS] n=55 R²=0.684 MAE=7,096kg

=== 2025-03-26 を予測中 (i=100) ===
[PROGRESS] n=56 R²=0.670 MAE=7,231kg

=== 2025-03-27 を予測中 (i=101) ===
[PROGRESS] n=56 R²=0.670 MAE=7,231kg

=== 2025-03-27 を予測中 (i=101) ===
[PROGRESS] n=57 R²=0.672 MAE=7,234kg

=== 2025-03-28 を予測中 (i=102) ===
[PROGRESS] n=57 R²=0.672 MAE=7,234kg

=== 2025-03-28 を予測中 (i=102) ===
[PROGRESS] n=58 R²=0.668 MAE=7,358kg

=== 2025-03-29 を予測中 (i=103) ===

In [10]:
# デバッグ: hol_min / hol_max の型確認用一時セル
print('sample hol_min/hol_max (from df_all tail)')
print(df_all['伝票日付'].tail(1), type(df_all['伝票日付'].iloc[-1]))

sample hol_min/hol_max (from df_all tail)
184249   2025-05-26
Name: 伝票日付, dtype: datetime64[ns] <class 'pandas._libs.tslibs.timestamps.Timestamp'>

In [11]:
# === 追加セル (このセルを特徴量削減セルより前に新規挿入) ===
# full_walkforward の現在シグネチャに合わせて余分な引数を自動的に除去し
# 戻り値を (actual, pred, model, dates) の4要素に正規化するラッパを直接適用します。
import sys
import inspect
import importlib

# パス設定を確実に行う
SCRIPT_ROOT = "/works/scripts"
if SCRIPT_ROOT not in sys.path:
    sys.path.insert(0, SCRIPT_ROOT)

# モジュールキャッシュをクリア
for name in list(sys.modules.keys()):
    if name.startswith('new_model2'):
        del sys.modules[name]

try:
    import new_model2.predict_model_v4_2_4 as _nm2p
    importlib.reload(_nm2p)
    print("[INFO] new_model2.predict_model_v4_2_4 successfully loaded and reloaded")
except Exception as e:
    print(f"[ERROR] Failed to load new_model2: {e}")
    # フォールバック: 前のセルで既に読み込まれたfull_walkforwardを使用
    from new_model2.predict_model_v4_2_4 import full_walkforward as _original_full_walkforward
    
    def _fw_wrapper(*args, **kwargs):
        # 引数フィルタリングなし（既存のfull_walkforwardをそのまま使用）
        res = _original_full_walkforward(*args, **kwargs)
        # 戻り値正規化
        if not isinstance(res, tuple):
            res = (res,)
        if len(res) == 2:
            actual, pred = res
            model = None
            dates = list(range(len(actual)))
        elif len(res) == 3:
            actual, pred, model = res
            dates = list(range(len(actual)))
        elif len(res) >= 4:
            actual, pred, model, dates = res[:4]
        else:
            actual, pred, model, dates = [], [], None, []
        return actual, pred, model, dates
    
    print("[INFO] Using fallback wrapper")
    # モジュール更新をスキップしてラッパーのみ適用
    import new_model2.predict_model_v4_2_4 as _nm2p
    _nm2p.full_walkforward = _fw_wrapper
    from new_model2.predict_model_v4_2_4 import full_walkforward
    print("[INFO] fallback wrapper installed (always returns 4要素)")
else:
    # 正常ロード時の処理
    _original_full_walkforward = _nm2p.full_walkforward
    _sig = inspect.signature(_original_full_walkforward)
    _supported = set(_sig.parameters.keys())
    print("[INFO] original full_walkforward signature:", _sig)

    def _fw_wrapper(*args, **kwargs):
        # 余分な引数を落とす
        filtered = {k:v for k,v in kwargs.items() if k in _supported}
        dropped = set(kwargs.keys()) - set(filtered.keys())
        if dropped:
            print(f"[WARN] 未サポート引数削除: {dropped}")
        res = _original_full_walkforward(*args, **filtered)
        # 戻り値正規化
        if not isinstance(res, tuple):
            res = (res,)
        if len(res) == 2:
            actual, pred = res
            model = None
            dates = list(range(len(actual)))
        elif len(res) == 3:
            actual, pred, model = res
            dates = list(range(len(actual)))
        elif len(res) >= 4:
            actual, pred, model, dates = res[:4]
        else:
            actual, pred, model, dates = [], [], None, []
        return actual, pred, model, dates

    # モンキーパッチ
    _nm2p.full_walkforward = _fw_wrapper
    from new_model2.predict_model_v4_2_4 import full_walkforward
    print("[INFO] wrapper installed (always returns 4要素)")

[INFO] new_model2.predict_model_v4_2_4 successfully loaded and reloaded
[INFO] original full_walkforward signature: (df_raw, holidays, df_reserve, df_weather, min_stage1_days, min_stage2_days, top_n=5, allowed_features=None)
[INFO] wrapper installed (always returns 4要素)

In [12]:
# === 365日実行結果の詳細分析 ===
print("=== 365日実行結果サマリー ===")
print(f"ベースラインMAE: {base_mae:.4f}")
print(f"予測回数: {len(base_err_df)}回")
print(f"データ期間: {hol_min} → {hol_max}")

if 'imp_all' in locals():
    print(f"\n=== 特徴量重要度トップ10 ===")
    print(imp_all.head(10))
    
    print(f"\n=== 削減候補特徴量（重要度下位5） ===")
    if len(reducible) >= 5:
        print(reducible.tail(5))
    else:
        print("削減候補が5個未満です")

if 'cand_mae' in locals():
    print(f"\n=== 削減テスト結果 ===")
    print(f"削除対象: {to_remove}")
    print(f"性能変化: {base_mae:.4f} → {cand_mae:.4f}")
    print(f"相対増加: {rel_inc*100:.2f}%")
    print(f"統計的有意性: p={p_value:.4f} ({method})")
    print(f"受容判定: {'ACCEPT' if accept else 'REJECT'}")
else:
    print("\n削減テストが未実行または失敗")

print(f"\n[INFO] 365日の長期データによる評価が完了しました")

=== 365日実行結果サマリー ===

NameError: name 'base_mae' is not defined

In [15]:
# --- 改良版 多段階削減ループ (true names) ---
from copy import deepcopy
import random
import math
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score

DEF_REL_MAE_TOL = 0.005  # 0.5% 悪化まで許容
DEF_REMOVE_STEP = 1

PROTECT_EXACT = set()
PROTECT_PREFIXES = ("合計",)

random.seed(42)
np.random.seed(42)

# === baseline が未定義ならここで自動生成 ===
_need_baseline = False
for _v in ["base_actual", "base_pred", "base_model", "base_dates"]:
    if _v not in globals():
        _need_baseline = True
        break

if _need_baseline:
    print('[INFO] baseline 未定義 -> 自動計算開始')
    try:
        # 祝日リスト再生成（存在すれば再利用）
        if 'holidays' not in globals():
            hol_min = df_all['伝票日付'].min()
            hol_max = df_all['伝票日付'].max()
            holidays = get_japanese_holidays(hol_min, hol_max)
        # パラメータ既定
        TOP_N = globals().get('TOP_N', 2)
        MIN_STAGE1_DAYS = globals().get('MIN_STAGE1_DAYS', 30)
        MIN_STAGE2_DAYS = globals().get('MIN_STAGE2_DAYS', 15)
        # 天気特徴量存在確認
        if 'df_weather_full' not in globals():
            try:
                from new_model2.feature_builder import WeatherFeatureBuilder
                wb = WeatherFeatureBuilder(start_date=df_all['伝票日付'].min(), end_date=df_all['伝票日付'].max(), enable_fallback=True)
                df_weather_full = wb.build()
                print(f"[INFO] weather built rows={len(df_weather_full)}")
            except Exception as e:
                print('[WARN] 天気特徴量生成失敗 -> なしで継続', e)
                df_weather_full = None
        # full_walkforward import (既にラッパ適用セルがある前提)
        try:
            from scripts.new_model2.predict_model_v4_2_4 import full_walkforward, get_target_items, get_feature_list
        except Exception:
            from new_model2.predict_model_v4_2_4 import full_walkforward, get_target_items, get_feature_list
        base_actual, base_pred, base_model, base_dates = full_walkforward(
            df_all, holidays, df_reserve, df_weather_full, MIN_STAGE1_DAYS, MIN_STAGE2_DAYS,
            top_n=TOP_N, allowed_features=None
        )
        print(f"[INFO] baseline 再計算完了 len={len(base_actual)}")
    except Exception as e:
        print('[ERROR] baseline 自動計算失敗:', e)
        base_actual, base_pred, base_model, base_dates = [], [], None, []

if len(base_actual) == 0:
    print('[ABORT] baseline が空のため特徴量削減をスキップ')
else:
    base_err_df = pd.DataFrame({
        'date': base_dates,
        'actual': base_actual,
        'pred': base_pred
    })
    base_err_df['abs_err'] = (base_err_df['actual'] - base_err_df['pred']).abs()
    base_mae = base_err_df['abs_err'].mean()
    base_r2 = r2_score(base_actual, base_pred) if len(base_actual)>1 else float('nan')
    print(f"[BASE] MAE={base_mae:,.2f} R2={base_r2:.3f} n={len(base_actual)}")

    # 重要度抽出
    imp_true = extract_true_feature_importances(base_model)
    all_features_ordered = imp_true['feature'].tolist()
    print(f"[INFO] feature count={len(all_features_ordered)}")

    # 保護対象除外
    reducible_df = imp_true[~imp_true['feature'].isin(PROTECT_EXACT)]
    for p in PROTECT_PREFIXES:
        reducible_df = reducible_df[~reducible_df['feature'].str.startswith(p)]

    # 重要度小さい順に並べ替え
    reducible_df = reducible_df.sort_values('abs_coef', ascending=True).reset_index(drop=True)

    current_keep = all_features_ordered.copy()
    history = []
    max_steps = 30

    # 安全のため TOP_N など再取得
    TOP_N = globals().get('TOP_N', 2)
    MIN_STAGE1_DAYS = globals().get('MIN_STAGE1_DAYS', 30)
    MIN_STAGE2_DAYS = globals().get('MIN_STAGE2_DAYS', 15)

    for step in range(max_steps):
        cand_remove = []
        for f in reducible_df['feature']:
            if f in current_keep and f not in PROTECT_EXACT and not any(f.startswith(p) for p in PROTECT_PREFIXES):
                cand_remove.append(f)
            if len(cand_remove) >= DEF_REMOVE_STEP:
                break
        if not cand_remove:
            print('[END] 除去候補なし')
            break

        tentative = [f for f in current_keep if f not in cand_remove]

        try:
            original_list = get_feature_list(get_target_items(df_all, TOP_N), extra_features=["天気_晴れ","天気_雨","天気_大雨","天気_台風"])
            tentative = [f for f in tentative if f in original_list]
        except Exception as e:
            print('[WARN] original_list取得失敗 -> スキップ', e)
        if len(tentative) == 0:
            print(f"[SKIP] step={step} 交差後特徴量ゼロ -> 中断")
            break

        print(f"\n[TRY] step={step} remove={cand_remove} -> tentative_len={len(tentative)}")

        cand_actual, cand_pred, cand_model, cand_dates = full_walkforward(
            df_all, holidays, df_reserve, df_weather_full, MIN_STAGE1_DAYS, MIN_STAGE2_DAYS,
            top_n=TOP_N, allowed_features=tentative
        )
        if len(cand_actual) < 3:
            print('[REJECT] データ不足')
            history.append({'step': step, 'removed': cand_remove, 'result': 'REJECT_DATA'})
            break

        cand_err = pd.DataFrame({'actual': cand_actual, 'pred': cand_pred})
        cand_err['abs_err'] = (cand_err['actual'] - cand_err['pred']).abs()
        cand_mae = cand_err['abs_err'].mean()
        cand_r2 = r2_score(cand_actual, cand_pred) if len(cand_actual)>1 else float('nan')

        rel_diff = (cand_mae - base_mae) / base_mae

        base_df_j = base_err_df.copy()
        base_df_j['date'] = base_dates
        cand_df_j = cand_err.copy()
        cand_df_j['date'] = cand_dates
        merged = base_df_j.merge(cand_df_j[['date','abs_err']], on='date', suffixes=('_base','_cand'))
        p_value = np.nan
        if len(merged) >= 5:
            try:
                from scipy.stats import wilcoxon
                stat, p_value = wilcoxon(merged['abs_err_base'], merged['abs_err_cand'])
            except Exception as e:
                print('[WARN] wilcoxon失敗', e)

        accept = (rel_diff <= DEF_REL_MAE_TOL) and (math.isnan(p_value) or p_value > 0.05)

        print(f"[EVAL] cand_mae={cand_mae:,.2f} (diff={rel_diff*100:.2f}%) R2={cand_r2:.3f} p={p_value if not math.isnan(p_value) else 'NA'} -> {'ACCEPT' if accept else 'REJECT'}")

        history.append({
            'step': step,
            'removed': cand_remove,
            'cand_mae': cand_mae,
            'cand_r2': cand_r2,
            'base_mae': base_mae,
            'base_r2': base_r2,
            'rel_diff': rel_diff,
            'p_value': p_value,
            'accept': accept
        })

        if accept:
            current_keep = tentative
            base_actual, base_pred, base_model, base_dates = cand_actual, cand_pred, cand_model, cand_dates
            base_err_df = cand_err.copy()
            base_err_df['date'] = base_dates
            base_mae = cand_mae
            base_r2 = cand_r2
            reducible_df = reducible_df[~reducible_df['feature'].isin(cand_remove)].reset_index(drop=True)
        else:
            PROTECT_EXACT.update(cand_remove)
            reducible_df = reducible_df[~reducible_df['feature'].isin(PROTECT_EXACT)].reset_index(drop=True)

        if len(reducible_df) == 0:
            print('[END] これ以上削減不可')
            break

    print('\n--- 削減履歴 ---')
    try:
        display(pd.DataFrame(history))
    except Exception:
        print(pd.DataFrame(history))

[INFO] baseline 未定義 -> 自動計算開始
▶️ full_walkforward(new_model2) 開始
[DEBUG] target_items=['混合廃棄物A', '混合廃棄物B']
[DEBUG] feature_list_len=23 (orig=23) df_feat_rows=751
[DEBUG] dates_len=751 min_stage1_days=20 min_stage2_days=10
[SKIP] 2023-01-14 (i=0) < min_stage1_days=20
[SKIP] 2023-01-19 (i=5) < min_stage1_days=20
[SKIP] 2023-01-24 (i=10) < min_stage1_days=20
[SKIP] 2023-01-29 (i=15) < min_stage1_days=20

=== 2023-02-03 を予測中 (i=20) ===
[DEBUG] feature_list_len=23 (orig=23) df_feat_rows=751
[DEBUG] dates_len=751 min_stage1_days=20 min_stage2_days=10
[SKIP] 2023-01-14 (i=0) < min_stage1_days=20
[SKIP] 2023-01-19 (i=5) < min_stage1_days=20
[SKIP] 2023-01-24 (i=10) < min_stage1_days=20
[SKIP] 2023-01-29 (i=15) < min_stage1_days=20

=== 2023-02-03 を予測中 (i=20) ===
[DEBUG] ステージ2未実行 rows=1/11

=== 2023-02-04 を予測中 (i=21) ===
[DEBUG] ステージ2未実行 rows=1/11

=== 2023-02-04 を予測中 (i=21) ===
[DEBUG] ステージ2未実行 rows=2/11

=== 2023-02-05 を予測中 (i=22) ===
[DEBUG] ステージ2未実行 rows=2/11

=== 2023-02-05 を予測中 (i=22) ===
[DEBUG] ステージ2未実行 rows=3/11

=== 2023-02-06 を予測中 (i=23) ===
[DEBUG] ステージ2未実行 rows=3/11

=== 2023-02-06 を予測中 (i=23) ===
[DEBUG] ステージ2未実行 rows=4/11

=== 2023-02-07 を予測中 (i=24) ===
[DEBUG] ステージ2未実行 rows=4/11

=== 2023-02-07 を予測中 (i=24) ===
[DEBUG] ステージ2未実行 rows=5/11

=== 2023-02-08 を予測中 (i=25) ===
[DEBUG] ステージ2未実行 rows=5/11

=== 2023-02-08 を予測中 (i=25) ===
[DEBUG] ステージ2未実行 rows=6/11

=== 2023-02-09 を予測中 (i=26) ===
[DEBUG] ステージ2未実行 rows=6/11

=== 2023-02-09 を予測中 (i=26) ===
[DEBUG] ステージ2未実行 rows=7/11

=== 2023-02-10 を予測中 (i=27) ===
[DEBUG] ステージ2未実行 rows=7/11

=== 2023-02-10 を予測中 (i=27) ===
[DEBUG] ステージ2未実行 rows=8/11

=== 2023-02-11 を予測中 (i=28) ===
[DEBUG] ステージ2未実行 rows=8/11

=== 2023-02-11 を予測中 (i=28) ===
[DEBUG] ステージ2未実行 rows=9/11

=== 2023-02-13 を予測中 (i=29) ===
[DEBUG] ステージ2未実行 rows=9/11

=== 2023-02-13 を予測中 (i=29) ===
[DEBUG] ステージ2未実行 rows=10/11

=== 2023-02-14 を予測中 (i=30) ===
[DEBUG] ステージ2未実行 rows=10/11

=== 2023-02-14 を予測中 (i=30) ===

=== 2023-02-15 を予測中 (i=31) ===

=== 2023-02-15 を予測中 (i=31) ===

=== 2023-02-16 を予測中 (i=32) ===

=== 2023-02-16 を予測中 (i=32) ===
[PROGRESS] n=3 R²=-0.928 MAE=5,563kg

=== 2023-02-17 を予測中 (i=33) ===
[PROGRESS] n=3 R²=-0.928 MAE=5,563kg

=== 2023-02-17 を予測中 (i=33) ===
[PROGRESS] n=4 R²=0.040 MAE=4,310kg

=== 2023-02-18 を予測中 (i=34) ===
[PROGRESS] n=4 R²=0.040 MAE=4,310kg

=== 2023-02-18 を予測中 (i=34) ===
[PROGRESS] n=5 R²=-1.994 MAE=6,526kg

=== 2023-02-19 を予測中 (i=35) ===
[PROGRESS] n=5 R²=-1.994 MAE=6,526kg

=== 2023-02-19 を予測中 (i=35) ===
[PROGRESS] n=6 R²=0.810 MAE=7,203kg

=== 2023-02-20 を予測中 (i=36) ===
[PROGRESS] n=6 R²=0.810 MAE=7,203kg

=== 2023-02-20 を予測中 (i=36) ===
[PROGRESS] n=7 R²=0.824 MAE=6,260kg

=== 2023-02-21 を予測中 (i=37) ===
[PROGRESS] n=7 R²=0.824 MAE=6,260kg

=== 2023-02-21 を予測中 (i=37) ===
[PROGRESS] n=8 R²=0.820 MAE=6,647kg

=== 2023-02-22 を予測中 (i=38) ===
[PROGRESS] n=8 R²=0.820 MAE=6,647kg

=== 2023-02-22 を予測中 (i=38) ===
[PROGRESS] n=9 R²=0.773 MAE=7,258kg

=== 2023-02-23 を予測中 (i=39) ===
[PROGRESS] n=9 R²=0.773 MAE=7,258kg

=== 2023-02-23 を予測中 (i=39) ===
[PROGRESS] n=10 R²=0.797 MAE=6,917kg

=== 2023-02-24 を予測中 (i=40) ===
[PROGRESS] n=10 R²=0.797 MAE=6,917kg

=== 2023-02-24 を予測中 (i=40) ===
[PROGRESS] n=11 R²=0.704 MAE=8,041kg

=== 2023-02-25 を予測中 (i=41) ===
[PROGRESS] n=11 R²=0.704 MAE=8,041kg

=== 2023-02-25 を予測中 (i=41) ===
[PROGRESS] n=12 R²=0.675 MAE=8,237kg

=== 2023-04-01 を予測中 (i=42) ===
[PROGRESS] n=12 R²=0.675 MAE=8,237kg

=== 2023-04-01 を予測中 (i=42) ===
[PROGRESS] n=13 R²=0.676 MAE=7,693kg

=== 2023-04-02 を予測中 (i=43) ===
[PROGRESS] n=13 R²=0.676 MAE=7,693kg

=== 2023-04-02 を予測中 (i=43) ===
[PROGRESS] n=14 R²=0.787 MAE=7,182kg

=== 2023-04-03 を予測中 (i=44) ===
[PROGRESS] n=14 R²=0.787 MAE=7,182kg

=== 2023-04-03 を予測中 (i=44) ===
[PROGRESS] n=15 R²=0.768 MAE=7,376kg

=== 2023-04-04 を予測中 (i=45) ===
[PROGRESS] n=15 R²=0.768 MAE=7,376kg

=== 2023-04-04 を予測中 (i=45) ===
[PROGRESS] n=16 R²=0.775 MAE=7,508kg

=== 2023-04-05 を予測中 (i=46) ===
[PROGRESS] n=16 R²=0.775 MAE=7,508kg

=== 2023-04-05 を予測中 (i=46) ===
[PROGRESS] n=17 R²=0.770 MAE=7,497kg

=== 2023-04-06 を予測中 (i=47) ===
[PROGRESS] n=17 R²=0.770 MAE=7,497kg

=== 2023-04-06 を予測中 (i=47) ===
[PROGRESS] n=18 R²=0.765 MAE=7,454kg

=== 2023-04-07 を予測中 (i=48) ===
[PROGRESS] n=18 R²=0.765 MAE=7,454kg

=== 2023-04-07 を予測中 (i=48) ===
[PROGRESS] n=19 R²=0.756 MAE=7,512kg

=== 2023-04-08 を予測中 (i=49) ===
[PROGRESS] n=19 R²=0.756 MAE=7,512kg

=== 2023-04-08 を予測中 (i=49) ===
[PROGRESS] n=20 R²=0.758 MAE=7,322kg

=== 2023-04-10 を予測中 (i=50) ===
[PROGRESS] n=20 R²=0.758 MAE=7,322kg

=== 2023-04-10 を予測中 (i=50) ===
[PROGRESS] n=21 R²=0.754 MAE=7,334kg

=== 2023-04-11 を予測中 (i=51) ===
[PROGRESS] n=21 R²=0.754 MAE=7,334kg

=== 2023-04-11 を予測中 (i=51) ===
[PROGRESS] n=22 R²=0.755 MAE=7,008kg

=== 2023-04-12 を予測中 (i=52) ===
[PROGRESS] n=22 R²=0.755 MAE=7,008kg

=== 2023-04-12 を予測中 (i=52) ===
[PROGRESS] n=23 R²=0.752 MAE=6,912kg

=== 2023-04-13 を予測中 (i=53) ===
[PROGRESS] n=23 R²=0.752 MAE=6,912kg

=== 2023-04-13 を予測中 (i=53) ===
[PROGRESS] n=24 R²=0.727 MAE=7,187kg

=== 2023-04-14 を予測中 (i=54) ===
[PROGRESS] n=24 R²=0.727 MAE=7,187kg

=== 2023-04-14 を予測中 (i=54) ===
[PROGRESS] n=25 R²=0.655 MAE=7,911kg

=== 2023-04-15 を予測中 (i=55) ===
[PROGRESS] n=25 R²=0.655 MAE=7,911kg

=== 2023-04-15 を予測中 (i=55) ===
[PROGRESS] n=26 R²=0.654 MAE=7,700kg

=== 2023-04-16 を予測中 (i=56) ===
[PROGRESS] n=26 R²=0.654 MAE=7,700kg

=== 2023-04-16 を予測中 (i=56) ===
[PROGRESS] n=27 R²=0.713 MAE=7,617kg

=== 2023-04-17 を予測中 (i=57) ===
[PROGRESS] n=27 R²=0.713 MAE=7,617kg

=== 2023-04-17 を予測中 (i=57) ===
[PROGRESS] n=28 R²=0.687 MAE=7,894kg

=== 2023-04-18 を予測中 (i=58) ===
[PROGRESS] n=28 R²=0.687 MAE=7,894kg

=== 2023-04-18 を予測中 (i=58) ===
[PROGRESS] n=29 R²=0.692 MAE=7,664kg

=== 2023-04-19 を予測中 (i=59) ===
[PROGRESS] n=29 R²=0.692 MAE=7,664kg

=== 2023-04-19 を予測中 (i=59) ===
[PROGRESS] n=30 R²=0.650 MAE=8,064kg

=== 2023-04-20 を予測中 (i=60) ===
[PROGRESS] n=30 R²=0.650 MAE=8,064kg

=== 2023-04-20 を予測中 (i=60) ===
[PROGRESS] n=31 R²=0.654 MAE=7,958kg

=== 2023-04-21 を予測中 (i=61) ===
[PROGRESS] n=31 R²=0.654 MAE=7,958kg

=== 2023-04-21 を予測中 (i=61) ===
[PROGRESS] n=32 R²=0.645 MAE=7,995kg

=== 2023-04-22 を予測中 (i=62) ===
[PROGRESS] n=32 R²=0.645 MAE=7,995kg

=== 2023-04-22 を予測中 (i=62) ===
[PROGRESS] n=33 R²=0.636 MAE=8,041kg

=== 2023-04-23 を予測中 (i=63) ===
[PROGRESS] n=33 R²=0.636 MAE=8,041kg

=== 2023-04-23 を予測中 (i=63) ===
[PROGRESS] n=34 R²=0.696 MAE=7,914kg

=== 2023-04-24 を予測中 (i=64) ===
[PROGRESS] n=34 R²=0.696 MAE=7,914kg

=== 2023-04-24 を予測中 (i=64) ===
[PROGRESS] n=35 R²=0.696 MAE=7,864kg

=== 2023-04-25 を予測中 (i=65) ===
[PROGRESS] n=35 R²=0.696 MAE=7,864kg

=== 2023-04-25 を予測中 (i=65) ===
[PROGRESS] n=36 R²=0.696 MAE=7,755kg

=== 2023-04-26 を予測中 (i=66) ===
[PROGRESS] n=36 R²=0.696 MAE=7,755kg

=== 2023-04-26 を予測中 (i=66) ===
[PROGRESS] n=37 R²=0.699 MAE=7,549kg

=== 2023-04-27 を予測中 (i=67) ===
[PROGRESS] n=37 R²=0.699 MAE=7,549kg

=== 2023-04-27 を予測中 (i=67) ===
[PROGRESS] n=38 R²=0.692 MAE=7,623kg

=== 2023-04-28 を予測中 (i=68) ===
[PROGRESS] n=38 R²=0.692 MAE=7,623kg

=== 2023-04-28 を予測中 (i=68) ===
[PROGRESS] n=39 R²=0.694 MAE=7,497kg

=== 2023-04-29 を予測中 (i=69) ===
[PROGRESS] n=39 R²=0.694 MAE=7,497kg

=== 2023-04-29 を予測中 (i=69) ===
[PROGRESS] n=40 R²=0.699 MAE=7,479kg

=== 2023-04-30 を予測中 (i=70) ===
[PROGRESS] n=40 R²=0.699 MAE=7,479kg

=== 2023-04-30 を予測中 (i=70) ===
[PROGRESS] n=41 R²=0.744 MAE=7,559kg

=== 2023-05-01 を予測中 (i=71) ===
[PROGRESS] n=41 R²=0.744 MAE=7,559kg

=== 2023-05-01 を予測中 (i=71) ===
[PROGRESS] n=42 R²=0.748 MAE=7,417kg

=== 2023-05-02 を予測中 (i=72) ===
[PROGRESS] n=42 R²=0.748 MAE=7,417kg

=== 2023-05-02 を予測中 (i=72) ===
[PROGRESS] n=43 R²=0.743 MAE=7,611kg

=== 2023-05-06 を予測中 (i=73) ===
[PROGRESS] n=43 R²=0.743 MAE=7,611kg

=== 2023-05-06 を予測中 (i=73) ===
[PROGRESS] n=44 R²=0.733 MAE=7,739kg

=== 2023-05-07 を予測中 (i=74) ===
[PROGRESS] n=44 R²=0.733 MAE=7,739kg

=== 2023-05-07 を予測中 (i=74) ===
[PROGRESS] n=45 R²=0.765 MAE=7,749kg

=== 2023-05-08 を予測中 (i=75) ===
[PROGRESS] n=45 R²=0.765 MAE=7,749kg

=== 2023-05-08 を予測中 (i=75) ===
[PROGRESS] n=46 R²=0.761 MAE=7,773kg

=== 2023-05-09 を予測中 (i=76) ===
[PROGRESS] n=46 R²=0.761 MAE=7,773kg

=== 2023-05-09 を予測中 (i=76) ===
[PROGRESS] n=47 R²=0.764 MAE=7,743kg

=== 2023-05-10 を予測中 (i=77) ===
[PROGRESS] n=47 R²=0.764 MAE=7,743kg

=== 2023-05-10 を予測中 (i=77) ===
[PROGRESS] n=48 R²=0.766 MAE=7,589kg

=== 2023-05-11 を予測中 (i=78) ===
[PROGRESS] n=48 R²=0.766 MAE=7,589kg

=== 2023-05-11 を予測中 (i=78) ===
[PROGRESS] n=49 R²=0.765 MAE=7,535kg

=== 2023-05-12 を予測中 (i=79) ===
[PROGRESS] n=49 R²=0.765 MAE=7,535kg

=== 2023-05-12 を予測中 (i=79) ===
[PROGRESS] n=50 R²=0.761 MAE=7,553kg

=== 2023-05-13 を予測中 (i=80) ===
[PROGRESS] n=50 R²=0.761 MAE=7,553kg

=== 2023-05-13 を予測中 (i=80) ===
[PROGRESS] n=51 R²=0.758 MAE=7,560kg

=== 2023-05-14 を予測中 (i=81) ===
[PROGRESS] n=51 R²=0.758 MAE=7,560kg

=== 2023-05-14 を予測中 (i=81) ===
[PROGRESS] n=52 R²=0.773 MAE=7,519kg

=== 2023-05-15 を予測中 (i=82) ===
[PROGRESS] n=52 R²=0.773 MAE=7,519kg

=== 2023-05-15 を予測中 (i=82) ===
[PROGRESS] n=53 R²=0.772 MAE=7,465kg

=== 2023-05-16 を予測中 (i=83) ===
[PROGRESS] n=53 R²=0.772 MAE=7,465kg

=== 2023-05-16 を予測中 (i=83) ===
[PROGRESS] n=54 R²=0.767 MAE=7,513kg

=== 2023-05-17 を予測中 (i=84) ===
[PROGRESS] n=54 R²=0.767 MAE=7,513kg

=== 2023-05-17 を予測中 (i=84) ===
[PROGRESS] n=55 R²=0.764 MAE=7,552kg

=== 2023-05-18 を予測中 (i=85) ===
[PROGRESS] n=55 R²=0.764 MAE=7,552kg

=== 2023-05-18 を予測中 (i=85) ===
[PROGRESS] n=56 R²=0.764 MAE=7,429kg

=== 2023-05-19 を予測中 (i=86) ===
[PROGRESS] n=56 R²=0.764 MAE=7,429kg

=== 2023-05-19 を予測中 (i=86) ===
[PROGRESS] n=57 R²=0.756 MAE=7,511kg

=== 2023-05-20 を予測中 (i=87) ===
[PROGRESS] n=57 R²=0.756 MAE=7,511kg

=== 2023-05-20 を予測中 (i=87) ===
[PROGRESS] n=58 R²=0.756 MAE=7,382kg

=== 2023-05-21 を予測中 (i=88) ===
[PROGRESS] n=58 R²=0.756 MAE=7,382kg

=== 2023-05-21 を予測中 (i=88) ===
[PROGRESS] n=59 R²=0.778 MAE=7,309kg

=== 2023-05-22 を予測中 (i=89) ===
[PROGRESS] n=59 R²=0.778 MAE=7,309kg

=== 2023-05-22 を予測中 (i=89) ===
[PROGRESS] n=60 R²=0.778 MAE=7,226kg

=== 2023-05-23 を予測中 (i=90) ===
[PROGRESS] n=60 R²=0.778 MAE=7,226kg

=== 2023-05-23 を予測中 (i=90) ===
[PROGRESS] n=61 R²=0.768 MAE=7,419kg

=== 2023-05-24 を予測中 (i=91) ===
[PROGRESS] n=61 R²=0.768 MAE=7,419kg

=== 2023-05-24 を予測中 (i=91) ===
[PROGRESS] n=62 R²=0.768 MAE=7,374kg

=== 2023-05-25 を予測中 (i=92) ===
[PROGRESS] n=62 R²=0.768 MAE=7,374kg

=== 2023-05-25 を予測中 (i=92) ===
[PROGRESS] n=63 R²=0.765 MAE=7,419kg

=== 2023-05-26 を予測中 (i=93) ===
[PROGRESS] n=63 R²=0.765 MAE=7,419kg

=== 2023-05-26 を予測中 (i=93) ===
[PROGRESS] n=64 R²=0.765 MAE=7,315kg

=== 2023-05-27 を予測中 (i=94) ===
[PROGRESS] n=64 R²=0.765 MAE=7,315kg

=== 2023-05-27 を予測中 (i=94) ===
[PROGRESS] n=65 R²=0.758 MAE=7,408kg

=== 2023-05-28 を予測中 (i=95) ===
[PROGRESS] n=65 R²=0.758 MAE=7,408kg

=== 2023-05-28 を予測中 (i=95) ===
[PROGRESS] n=66 R²=0.766 MAE=7,511kg

=== 2023-05-29 を予測中 (i=96) ===
[PROGRESS] n=66 R²=0.766 MAE=7,511kg

=== 2023-05-29 を予測中 (i=96) ===
[PROGRESS] n=67 R²=0.766 MAE=7,424kg

=== 2023-05-30 を予測中 (i=97) ===
[PROGRESS] n=67 R²=0.766 MAE=7,424kg

=== 2023-05-30 を予測中 (i=97) ===
[PROGRESS] n=68 R²=0.766 MAE=7,315kg

=== 2023-05-31 を予測中 (i=98) ===
[PROGRESS] n=68 R²=0.766 MAE=7,315kg

=== 2023-05-31 を予測中 (i=98) ===
[PROGRESS] n=69 R²=0.766 MAE=7,295kg

=== 2023-06-01 を予測中 (i=99) ===
[PROGRESS] n=69 R²=0.766 MAE=7,295kg

=== 2023-06-01 を予測中 (i=99) ===
[PROGRESS] n=70 R²=0.761 MAE=7,366kg

=== 2023-06-02 を予測中 (i=100) ===
[PROGRESS] n=70 R²=0.761 MAE=7,366kg

=== 2023-06-02 を予測中 (i=100) ===
[PROGRESS] n=71 R²=0.761 MAE=7,295kg

=== 2023-06-03 を予測中 (i=101) ===
[PROGRESS] n=71 R²=0.761 MAE=7,295kg

=== 2023-06-03 を予測中 (i=101) ===
[PROGRESS] n=72 R²=0.757 MAE=7,344kg

=== 2023-06-04 を予測中 (i=102) ===
[PROGRESS] n=72 R²=0.757 MAE=7,344kg

=== 2023-06-04 を予測中 (i=102) ===
[PROGRESS] n=73 R²=0.768 MAE=7,331kg

=== 2023-06-05 を予測中 (i=103) ===
[PROGRESS] n=73 R²=0.768 MAE=7,331kg

=== 2023-06-05 を予測中 (i=103) ===
[PROGRESS] n=74 R²=0.767 MAE=7,315kg

=== 2023-06-06 を予測中 (i=104) ===
[PROGRESS] n=74 R²=0.767 MAE=7,315kg

=== 2023-06-06 を予測中 (i=104) ===
[PROGRESS] n=75 R²=0.763 MAE=7,363kg

=== 2023-06-07 を予測中 (i=105) ===
[PROGRESS] n=75 R²=0.763 MAE=7,363kg

=== 2023-06-07 を予測中 (i=105) ===
[PROGRESS] n=76 R²=0.764 MAE=7,337kg

=== 2023-06-08 を予測中 (i=106) ===
[PROGRESS] n=76 R²=0.764 MAE=7,337kg

=== 2023-06-08 を予測中 (i=106) ===
[PROGRESS] n=77 R²=0.764 MAE=7,267kg

=== 2023-06-09 を予測中 (i=107) ===
[PROGRESS] n=77 R²=0.764 MAE=7,267kg

=== 2023-06-09 を予測中 (i=107) ===
[PROGRESS] n=78 R²=0.764 MAE=7,187kg

=== 2023-06-10 を予測中 (i=108) ===
[PROGRESS] n=78 R²=0.764 MAE=7,187kg

=== 2023-06-10 を予測中 (i=108) ===
[PROGRESS] n=79 R²=0.764 MAE=7,160kg

=== 2023-06-12 を予測中 (i=109) ===
[PROGRESS] n=79 R²=0.764 MAE=7,160kg

=== 2023-06-12 を予測中 (i=109) ===
[PROGRESS] n=80 R²=0.754 MAE=7,307kg

=== 2023-06-13 を予測中 (i=110) ===
[PROGRESS] n=80 R²=0.754 MAE=7,307kg

=== 2023-06-13 を予測中 (i=110) ===
[PROGRESS] n=81 R²=0.754 MAE=7,260kg

=== 2023-06-14 を予測中 (i=111) ===
[PROGRESS] n=81 R²=0.754 MAE=7,260kg

=== 2023-06-14 を予測中 (i=111) ===
[PROGRESS] n=82 R²=0.744 MAE=7,470kg

=== 2023-06-15 を予測中 (i=112) ===
[PROGRESS] n=82 R²=0.744 MAE=7,470kg

=== 2023-06-15 を予測中 (i=112) ===
[PROGRESS] n=83 R²=0.745 MAE=7,448kg

=== 2023-06-16 を予測中 (i=113) ===
[PROGRESS] n=83 R²=0.745 MAE=7,448kg

=== 2023-06-16 を予測中 (i=113) ===
[PROGRESS] n=84 R²=0.732 MAE=7,586kg

=== 2023-06-17 を予測中 (i=114) ===
[PROGRESS] n=84 R²=0.732 MAE=7,586kg

=== 2023-06-17 を予測中 (i=114) ===
[PROGRESS] n=85 R²=0.732 MAE=7,527kg

=== 2023-06-18 を予測中 (i=115) ===
[PROGRESS] n=86 R²=0.739 MAE=7,535kg

=== 2023-06-19 を予測中 (i=116) ===
[PROGRESS] n=86 R²=0.739 MAE=7,535kg

=== 2023-06-19 を予測中 (i=116) ===
[PROGRESS] n=87 R²=0.738 MAE=7,517kg

=== 2023-06-20 を予測中 (i=117) ===
[PROGRESS] n=87 R²=0.738 MAE=7,517kg

=== 2023-06-20 を予測中 (i=117) ===
[PROGRESS] n=88 R²=0.739 MAE=7,438kg

=== 2023-06-21 を予測中 (i=118) ===
[PROGRESS] n=88 R²=0.739 MAE=7,438kg

=== 2023-06-21 を予測中 (i=118) ===
[PROGRESS] n=89 R²=0.739 MAE=7,456kg

=== 2023-06-22 を予測中 (i=119) ===
[PROGRESS] n=89 R²=0.739 MAE=7,456kg

=== 2023-06-22 を予測中 (i=119) ===
[PROGRESS] n=90 R²=0.730 MAE=7,605kg

=== 2023-06-23 を予測中 (i=120) ===
[PROGRESS] n=90 R²=0.730 MAE=7,605kg

=== 2023-06-23 を予測中 (i=120) ===
[PROGRESS] n=91 R²=0.730 MAE=7,541kg

=== 2023-06-24 を予測中 (i=121) ===
[PROGRESS] n=91 R²=0.730 MAE=7,541kg

=== 2023-06-24 を予測中 (i=121) ===
[PROGRESS] n=92 R²=0.730 MAE=7,492kg

=== 2023-06-25 を予測中 (i=122) ===
[PROGRESS] n=92 R²=0.730 MAE=7,492kg

=== 2023-06-25 を予測中 (i=122) ===
[PROGRESS] n=93 R²=0.743 MAE=7,418kg

=== 2023-06-26 を予測中 (i=123) ===
[PROGRESS] n=93 R²=0.743 MAE=7,418kg

=== 2023-06-26 を予測中 (i=123) ===
[PROGRESS] n=94 R²=0.735 MAE=7,533kg

=== 2023-06-27 を予測中 (i=124) ===
[PROGRESS] n=94 R²=0.735 MAE=7,533kg

=== 2023-06-27 を予測中 (i=124) ===
[PROGRESS] n=95 R²=0.733 MAE=7,537kg

=== 2023-06-28 を予測中 (i=125) ===
[PROGRESS] n=95 R²=0.733 MAE=7,537kg

=== 2023-06-28 を予測中 (i=125) ===
[PROGRESS] n=96 R²=0.731 MAE=7,560kg

=== 2023-06-29 を予測中 (i=126) ===
[PROGRESS] n=96 R²=0.731 MAE=7,560kg

=== 2023-06-29 を予測中 (i=126) ===
[PROGRESS] n=97 R²=0.731 MAE=7,498kg

=== 2023-06-30 を予測中 (i=127) ===
[PROGRESS] n=97 R²=0.731 MAE=7,498kg

=== 2023-06-30 を予測中 (i=127) ===
[PROGRESS] n=98 R²=0.731 MAE=7,434kg

=== 2023-07-01 を予測中 (i=128) ===
[PROGRESS] n=98 R²=0.731 MAE=7,434kg

=== 2023-07-01 を予測中 (i=128) ===
[PROGRESS] n=99 R²=0.725 MAE=7,498kg

=== 2023-07-02 を予測中 (i=129) ===
[PROGRESS] n=99 R²=0.725 MAE=7,498kg

=== 2023-07-02 を予測中 (i=129) ===
[PROGRESS] n=100 R²=0.741 MAE=7,489kg

=== 2023-07-03 を予測中 (i=130) ===
[PROGRESS] n=100 R²=0.741 MAE=7,489kg

=== 2023-07-03 を予測中 (i=130) ===
[PROGRESS] n=101 R²=0.739 MAE=7,500kg

=== 2023-07-04 を予測中 (i=131) ===
[PROGRESS] n=101 R²=0.739 MAE=7,500kg

=== 2023-07-04 を予測中 (i=131) ===
[PROGRESS] n=102 R²=0.740 MAE=7,470kg

=== 2023-07-05 を予測中 (i=132) ===
[PROGRESS] n=102 R²=0.740 MAE=7,470kg

=== 2023-07-05 を予測中 (i=132) ===
[PROGRESS] n=103 R²=0.739 MAE=7,457kg

=== 2023-07-06 を予測中 (i=133) ===
[PROGRESS] n=103 R²=0.739 MAE=7,457kg

=== 2023-07-06 を予測中 (i=133) ===
[PROGRESS] n=104 R²=0.740 MAE=7,396kg

=== 2023-07-07 を予測中 (i=134) ===
[PROGRESS] n=104 R²=0.740 MAE=7,396kg

=== 2023-07-07 を予測中 (i=134) ===
[PROGRESS] n=105 R²=0.739 MAE=7,388kg

=== 2023-07-08 を予測中 (i=135) ===
[PROGRESS] n=105 R²=0.739 MAE=7,388kg

=== 2023-07-08 を予測中 (i=135) ===
[PROGRESS] n=106 R²=0.737 MAE=7,396kg

=== 2023-07-10 を予測中 (i=136) ===
[PROGRESS] n=106 R²=0.737 MAE=7,396kg

=== 2023-07-10 を予測中 (i=136) ===
[PROGRESS] n=107 R²=0.738 MAE=7,348kg

=== 2023-07-11 を予測中 (i=137) ===
[PROGRESS] n=107 R²=0.738 MAE=7,348kg

=== 2023-07-11 を予測中 (i=137) ===
[PROGRESS] n=108 R²=0.738 MAE=7,314kg

=== 2023-07-12 を予測中 (i=138) ===
[PROGRESS] n=108 R²=0.738 MAE=7,314kg

=== 2023-07-12 を予測中 (i=138) ===
[PROGRESS] n=109 R²=0.738 MAE=7,319kg

=== 2023-07-13 を予測中 (i=139) ===
[PROGRESS] n=109 R²=0.738 MAE=7,319kg

=== 2023-07-13 を予測中 (i=139) ===
[PROGRESS] n=110 R²=0.736 MAE=7,337kg

=== 2023-07-14 を予測中 (i=140) ===
[PROGRESS] n=110 R²=0.736 MAE=7,337kg

=== 2023-07-14 を予測中 (i=140) ===
[PROGRESS] n=111 R²=0.733 MAE=7,356kg

=== 2023-07-15 を予測中 (i=141) ===
[PROGRESS] n=111 R²=0.733 MAE=7,356kg

=== 2023-07-15 を予測中 (i=141) ===
[PROGRESS] n=112 R²=0.729 MAE=7,403kg

=== 2023-07-16 を予測中 (i=142) ===
[PROGRESS] n=112 R²=0.729 MAE=7,403kg

=== 2023-07-16 を予測中 (i=142) ===
[PROGRESS] n=113 R²=0.739 MAE=7,345kg

=== 2023-07-17 を予測中 (i=143) ===
[PROGRESS] n=113 R²=0.739 MAE=7,345kg

=== 2023-07-17 を予測中 (i=143) ===
[PROGRESS] n=114 R²=0.745 MAE=7,316kg

=== 2023-07-18 を予測中 (i=144) ===
[PROGRESS] n=114 R²=0.745 MAE=7,316kg

=== 2023-07-18 を予測中 (i=144) ===
[PROGRESS] n=115 R²=0.739 MAE=7,385kg

=== 2023-07-19 を予測中 (i=145) ===
[PROGRESS] n=115 R²=0.739 MAE=7,385kg

=== 2023-07-19 を予測中 (i=145) ===
[PROGRESS] n=116 R²=0.739 MAE=7,357kg

=== 2023-07-20 を予測中 (i=146) ===
[PROGRESS] n=116 R²=0.739 MAE=7,357kg

=== 2023-07-20 を予測中 (i=146) ===
[PROGRESS] n=117 R²=0.729 MAE=7,458kg

=== 2023-07-21 を予測中 (i=147) ===
[PROGRESS] n=117 R²=0.729 MAE=7,458kg

=== 2023-07-21 を予測中 (i=147) ===
[PROGRESS] n=118 R²=0.720 MAE=7,598kg

=== 2023-07-22 を予測中 (i=148) ===
[PROGRESS] n=118 R²=0.720 MAE=7,598kg

=== 2023-07-22 を予測中 (i=148) ===
[PROGRESS] n=119 R²=0.719 MAE=7,600kg

=== 2023-07-23 を予測中 (i=149) ===
[PROGRESS] n=119 R²=0.719 MAE=7,600kg

=== 2023-07-23 を予測中 (i=149) ===
[PROGRESS] n=120 R²=0.730 MAE=7,556kg

=== 2023-07-24 を予測中 (i=150) ===
[PROGRESS] n=120 R²=0.730 MAE=7,556kg

=== 2023-07-24 を予測中 (i=150) ===
[PROGRESS] n=121 R²=0.730 MAE=7,542kg

=== 2023-07-25 を予測中 (i=151) ===
[PROGRESS] n=121 R²=0.730 MAE=7,542kg

=== 2023-07-25 を予測中 (i=151) ===
[PROGRESS] n=122 R²=0.731 MAE=7,486kg

=== 2023-07-26 を予測中 (i=152) ===
[PROGRESS] n=122 R²=0.731 MAE=7,486kg

=== 2023-07-26 を予測中 (i=152) ===
[PROGRESS] n=123 R²=0.732 MAE=7,432kg

=== 2023-07-27 を予測中 (i=153) ===
[PROGRESS] n=123 R²=0.732 MAE=7,432kg

=== 2023-07-27 を予測中 (i=153) ===
[PROGRESS] n=124 R²=0.733 MAE=7,377kg

=== 2023-07-28 を予測中 (i=154) ===
[PROGRESS] n=124 R²=0.733 MAE=7,377kg

=== 2023-07-28 を予測中 (i=154) ===
[PROGRESS] n=125 R²=0.732 MAE=7,376kg

=== 2023-07-29 を予測中 (i=155) ===
[PROGRESS] n=125 R²=0.732 MAE=7,376kg

=== 2023-07-29 を予測中 (i=155) ===
[PROGRESS] n=126 R²=0.723 MAE=7,486kg

=== 2023-07-30 を予測中 (i=156) ===
[PROGRESS] n=126 R²=0.723 MAE=7,486kg

=== 2023-07-30 を予測中 (i=156) ===
[PROGRESS] n=127 R²=0.734 MAE=7,441kg

=== 2023-07-31 を予測中 (i=157) ===
[PROGRESS] n=127 R²=0.734 MAE=7,441kg

=== 2023-07-31 を予測中 (i=157) ===
[PROGRESS] n=128 R²=0.734 MAE=7,403kg

=== 2023-08-01 を予測中 (i=158) ===
[PROGRESS] n=128 R²=0.734 MAE=7,403kg

=== 2023-08-01 を予測中 (i=158) ===
[PROGRESS] n=129 R²=0.734 MAE=7,376kg

=== 2023-08-02 を予測中 (i=159) ===
[PROGRESS] n=129 R²=0.734 MAE=7,376kg

=== 2023-08-02 を予測中 (i=159) ===
[PROGRESS] n=130 R²=0.732 MAE=7,378kg

=== 2023-08-03 を予測中 (i=160) ===
[PROGRESS] n=130 R²=0.732 MAE=7,378kg

=== 2023-08-03 を予測中 (i=160) ===
[PROGRESS] n=131 R²=0.732 MAE=7,369kg

=== 2023-08-04 を予測中 (i=161) ===
[PROGRESS] n=131 R²=0.732 MAE=7,369kg

=== 2023-08-04 を予測中 (i=161) ===

NameError: name 'extract_true_feature_importances' is not defined

In [ ]:
# === 最終特徴量サマリー & 再学習・保存ユーティリティ ===
import os, json, pickle, time
from datetime import datetime

# current_keep が存在し、最低限の特徴があるか確認
if 'current_keep' not in globals() or not current_keep:
    print('[FINAL] current_keep が未定義または空のためスキップ')
else:
    print(f'[FINAL] 最終特徴量数: {len(current_keep)}')
    print(current_keep[:30] + (['...'] if len(current_keep) > 30 else []))

    # 祝日と天気を再利用 / 無ければ再生成
    try:
        holidays
    except NameError:
        hol_min = df_all['伝票日付'].min(); hol_max = df_all['伝票日付'].max()
        holidays = get_japanese_holidays(hol_min, hol_max)
    try:
        df_weather_full
    except NameError:
        df_weather_full = None

    # パラメータ取得（存在しなければデフォルト）
    TOP_N = globals().get('TOP_N', 2)
    MIN_STAGE1_DAYS = globals().get('MIN_STAGE1_DAYS', 30)
    MIN_STAGE2_DAYS = globals().get('MIN_STAGE2_DAYS', 15)

    # full_walkforward import（ラッパ適用済み想定）
    try:
        from scripts.new_model2.predict_model_v4_2_4 import full_walkforward
    except Exception:
        from new_model2.predict_model_v4_2_4 import full_walkforward

    print('[FINAL] 最終特徴量で再学習開始')
    t0 = time.time()
    f_actual, f_pred, f_model, f_dates = full_walkforward(
        df_all, holidays, df_reserve, df_weather_full,
        MIN_STAGE1_DAYS, MIN_STAGE2_DAYS,
        top_n=TOP_N, allowed_features=current_keep
    )
    if len(f_actual) == 0:
        print('[FINAL][ERROR] 再学習結果が空')
    else:
        from sklearn.metrics import r2_score, mean_absolute_error
        f_mae = mean_absolute_error(f_actual, f_pred)
        f_r2 = r2_score(f_actual, f_pred) if len(f_actual) > 1 else float('nan')
        print(f'[FINAL] 再学習完了 MAE={f_mae:,.2f} R2={f_r2:.3f} n={len(f_actual)} elapsed={(time.time()-t0):.1f}s')

        # 出力ディレクトリ
        out_dir = '/works/data'
        os.makedirs(out_dir, exist_ok=True)

        # 特徴量リスト保存
        feat_path = os.path.join(out_dir, 'selected_features_final.txt')
        with open(feat_path, 'w', encoding='utf-8') as f:
            for feat in current_keep:
                f.write(feat + '\n')
        print('[FINAL] 特徴量リスト保存:', feat_path)

        # メタ情報 + 成果指標
        meta = {
            'generated_at': datetime.utcnow().isoformat() + 'Z',
            'feature_count': len(current_keep),
            'mae': f_mae,
            'r2': f_r2,
            'n_predictions': len(f_actual),
            'params': {
                'TOP_N': TOP_N,
                'MIN_STAGE1_DAYS': MIN_STAGE1_DAYS,
                'MIN_STAGE2_DAYS': MIN_STAGE2_DAYS,
                'REL_MAE_TOL': DEF_REL_MAE_TOL,
                'REMOVE_STEP': DEF_REMOVE_STEP
            }
        }
        meta_path = os.path.join(out_dir, 'final_model_meta.json')
        with open(meta_path, 'w', encoding='utf-8') as f:
            json.dump(meta, f, ensure_ascii=False, indent=2)
        print('[FINAL] メタ情報保存:', meta_path)

        # モデル保存（stage1_model_dict を pickle）
        try:
            model_path = os.path.join(out_dir, 'final_stage1_model.pkl')
            with open(model_path, 'wb') as f:
                pickle.dump(f_model, f)
            print('[FINAL] モデル保存:', model_path)
        except Exception as e:
            print('[FINAL][WARN] モデル保存失敗:', e)

        # 簡易差分 (baseline との差) があれば表示
        try:
            diff_mae = (f_mae - base_mae) / base_mae * 100
            print(f'[FINAL] baselineとの差: MAE差分={diff_mae:.2f}%')
        except Exception:
            pass